// Auto-generated by @farming-labs/next — do not edit manually.

import "@farming-labs/next/api-reference.css";
import docsConfig from "@/docs.config";
import { createNextApiReferencePage } from "@farming-labs/next/api-reference";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const ApiReferencePage = createNextApiReferencePage(docsConfig);

export default ApiReferencePage;
