/**
 * @farming-labs/docs
 *
 * Modern, flexible MDX-based docs framework with themes and SEO support.
 * Inspired by Fumadocs: https://github.com/fuma-nama/fumadocs
 *
 * Framework-agnostic core - works with Next.js, Vite, etc.
 */

import type { DocsConfig } from "./types.js";

export { defineDocs } from "./define-docs.js";
export { createDocsCloudAnalytics } from "./cloud-analytics.js";
export {
  DOCS_AGENT_TRACE_EVENT_TYPES,
  createDocsAgentTraceContext,
  createDocsAgentTraceId,
  emitDocsAgentTraceEvent,
  emitDocsAnalyticsEvent,
  emitDocsObservabilityEvent,
  resolveDocsAnalyticsConfig,
  resolveDocsObservabilityConfig,
} from "./analytics.js";
export { resolveChangelogConfig } from "./changelog.js";
export { deepMerge } from "./utils.js";
export { createTheme, extendTheme } from "./create-theme.js";
export { resolveDocsI18n, resolveDocsLocale, resolveDocsPath } from "./i18n.js";
export {
  buildDocsPageStructuredData,
  buildPageOpenGraph,
  buildPageTwitter,
  renderDocsPageStructuredDataJson,
  resolveDocsMetadataBaseUrl,
  resolveOGImage,
  resolveTitle,
} from "./metadata.js";
export {
  estimateReadingTimeMinutes,
  resolvePageReadingTime,
  resolveReadingTimeFromContent,
  resolveReadingTimeFromSource,
  resolveReadingTimeOptions,
} from "./reading-time.js";
export { normalizeDocsRelated, renderDocsRelatedMarkdownLines } from "./related.js";
export {
  applySidebarFolderIndexBehavior,
  resolvePageSidebarFolderIndexBehavior,
  resolveSidebarFolderIndexBehavior,
  resolveSidebarFolderIndexBehaviorForPath,
} from "./sidebar.js";
export {
  GENERATED_AGENT_PROVENANCE_MARKER,
  GENERATED_AGENT_PROVENANCE_VERSION,
  hashGeneratedAgentContent,
  normalizeGeneratedAgentContent,
  parseGeneratedAgentDocument,
  serializeGeneratedAgentDocument,
  stripGeneratedAgentProvenance,
} from "./agent-provenance.js";
export {
  DEFAULT_AGENT_FEEDBACK_ROUTE,
  DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA,
  DEFAULT_AGENT_MD_ROUTE,
  DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  DEFAULT_AGENT_SPEC_ROUTE,
  DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE,
  DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE,
  DEFAULT_AGENTS_MD_ROUTE,
  DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
  DEFAULT_DOCS_API_ROUTE,
  DEFAULT_OPENAPI_SCHEMA_ROUTE,
  DEFAULT_LLMS_FULL_TXT_ROUTE,
  DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE,
  DEFAULT_LLMS_TXT_MAX_CHARS,
  DEFAULT_LLMS_TXT_ROUTE,
  DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE,
  DEFAULT_MCP_PUBLIC_ROUTE,
  DEFAULT_MCP_ROUTE,
  DEFAULT_MCP_WELL_KNOWN_ROUTE,
  DEFAULT_SKILL_MD_ROUTE,
  DEFAULT_SKILL_MD_WELL_KNOWN_ROUTE,
  DOCS_MARKDOWN_SIGNATURE_AGENT_HEADER,
  buildDocsAgentDiscoverySpec,
  buildDocsAgentFeedbackSchema,
  buildDocsMcpEndpointCandidates,
  findDocsMarkdownPage,
  getDocsMarkdownCanonicalLinkHeader,
  getDocsMarkdownVaryHeader,
  hasDocsMarkdownSignatureAgent,
  isDocsAgentDiscoveryRequest,
  isDocsAgentsRequest,
  isDocsLlmsTxtPublicRequest,
  isDocsMcpRequest,
  isDocsPublicGetRequest,
  isDocsSkillRequest,
  normalizeDocsPathSegment,
  normalizeDocsUrlPath,
  getDocsLlmsTxtMaxCharsIssue,
  matchesDocsLlmsTxtSection,
  renderDocsMarkdownDocument,
  renderDocsMarkdownNotFound,
  renderDocsLlmsTxt,
  renderDocsAgentsDocument,
  renderDocsSkillDocument,
  parseDocsAgentFeedbackData,
  resolveDocsAgentFeedbackConfig,
  resolveDocsAgentFeedbackRequest,
  resolveDocsAgentsFormat,
  resolveDocsMarkdownCanonicalUrl,
  resolveDocsAgentMdxContent,
  resolveDocsLlmsTxtRequest,
  resolveDocsLlmsTxtSections,
  resolveDocsLlmsTxtFormat,
  resolveDocsOpenApiDiscoveryConfig,
  selectDocsLlmsTxtContent,
  resolveDocsSkillFormat,
  resolveDocsMarkdownRequest,
  toDocsMarkdownUrl,
  validateDocsAgentFeedbackPayload,
} from "./agent.js";
export type {
  DocsAgentsDocumentOptions,
  DocsAgentFeedbackRequest,
  DocsAgentFeedbackResolvedConfig,
  DocsLlmsTxtGeneratedContent,
  DocsLlmsTxtGeneratedSection,
  DocsLlmsTxtMaxCharsIssue,
  DocsLlmsTxtPageInput,
  DocsLlmsTxtRequest,
  DocsLlmsTxtResolvedMaxChars,
  DocsLlmsTxtResolvedSection,
  DocsLlmsTxtSelectedContent,
  DocsMcpEndpointCandidate,
  DocsMcpEndpointCandidateOptions,
  DocsOpenApiDiscoveryConfig,
  DocsOpenApiResolvedDiscoveryConfig,
} from "./agent.js";
export type {
  PromptAction,
  PromptProviderChoice,
  SerializeOpenDocsProviderOptions,
  SerializedOpenDocsProvider,
} from "./prompt-utils.js";
export {
  DEFAULT_SITEMAP_MANIFEST_PATH,
  DEFAULT_SITEMAP_MD_DOCS_ROUTE,
  DEFAULT_SITEMAP_MD_ROUTE,
  DEFAULT_SITEMAP_MD_WELL_KNOWN_ROUTE,
  DEFAULT_SITEMAP_XML_ROUTE,
  buildDocsSitemapManifest,
  createDocsSitemapResponse,
  readDocsSitemapManifestFromContentMap,
  renderDocsSitemapMarkdown,
  renderDocsSitemapXml,
  resolveDocsSitemapPageLastmod,
  resolveDocsSitemapConfig,
  resolveDocsSitemapRequest,
  toDocsSitemapMarkdownUrl,
} from "./sitemap.js";
export {
  DEFAULT_DOCS_AI_ROBOTS_USER_AGENTS,
  DEFAULT_ROBOTS_TXT_ROUTE,
  DOCS_ROBOTS_GENERATED_BLOCK_END,
  DOCS_ROBOTS_GENERATED_BLOCK_START,
  analyzeDocsRobotsTxt,
  createDocsRobotsResponse,
  getDocsRobotsAllowRoutes,
  renderDocsRobotsGeneratedBlock,
  renderDocsRobotsTxt,
  resolveDocsRobotsConfig,
  resolveDocsRobotsRequest,
  upsertDocsRobotsGeneratedBlock,
} from "./robots.js";
export type {
  DocsSitemapFormat,
  DocsSitemapManifest,
  DocsSitemapManifestPage,
  DocsSitemapPageInput,
  DocsSitemapResolvedConfig,
} from "./sitemap.js";
export type { DocsRobotsResolvedConfig, DocsRobotsRenderOptions } from "./robots.js";
export {
  buildDocsSearchDocuments,
  buildDocsAskAIContext,
  createAlgoliaSearchAdapter,
  createCustomSearchAdapter,
  createMcpSearchAdapter,
  createSimpleSearchAdapter,
  createTypesenseSearchAdapter,
  formatDocsAskAIPackageHints,
  inferDocsAskAIPackageHints,
  performDocsSearch,
  resolveAskAISearchRequestConfig,
  resolveSearchRequestConfig,
} from "./search.js";
export type { GeneratedAgentProvenance, GeneratedAgentSourceKind } from "./agent-provenance.js";
export type {
  DocsConfig,
  LlmsTxtConfig,
  LlmsTxtMaxCharsConfig,
  LlmsTxtMaxCharsMode,
  LlmsTxtSectionConfig,
  DocsSitemapConfig,
  DocsRobotsConfig,
  DocsRobotsRule,
  ChangelogConfig,
  ChangelogFrontmatter,
  ApiReferenceConfig,
  ApiReferenceRenderer,
  DocsI18nConfig,
  DocsMcpConfig,
  DocsMcpToolsConfig,
  DocsReviewCiConfig,
  DocsReviewCiMode,
  DocsReviewConfig,
  DocsReviewRulesConfig,
  DocsReviewScoreConfig,
  DocsReviewSeverity,
  DocsNav,
  DocsTheme,
  DocsMetadata,
  OGConfig,
  OpenGraphImage,
  PageOpenGraph,
  PageTwitter,
  DocsRelatedItem,
  ResolvedDocsRelatedLink,
  UIConfig,
  FontStyle,
  TypographyConfig,
  PageFrontmatter,
  PageSidebarFrontmatter,
  ThemeToggleConfig,
  BreadcrumbConfig,
  SidebarConfig,
  SidebarComponentProps,
  SidebarFolderIndexBehavior,
  SidebarTree,
  SidebarNode,
  SidebarPageNode,
  SidebarFolderNode,
  PageActionsConfig,
  CopyMarkdownConfig,
  OpenDocsConfig,
  OpenDocsProvider,
  OpenDocsProviderConfig,
  OpenDocsProviderId,
  OpenDocsTarget,
  GithubConfig,
  AIConfig,
  DocsAskAIActionData,
  DocsAskAIActionType,
  DocsAskAIFeedbackConfig,
  DocsAskAIFeedbackData,
  DocsAskAIFeedbackMessage,
  DocsAskAIFeedbackValue,
  OrderingItem,
  LastUpdatedConfig,
  ReadingTimeConfig,
  CodeBlockCopyData,
  DocsFeedbackValue,
  DocsFeedbackData,
  DocsAgentFeedbackContext,
  DocsAgentFeedbackData,
  FeedbackConfig,
  AgentFeedbackConfig,
  DocsAskAIMcpConfig,
  DocsSearchAdapter,
  DocsSearchAdapterContext,
  DocsSearchAdapterFactory,
  DocsSearchChunkingConfig,
  DocsSearchConfig,
  DocsSearchDocument,
  DocsSearchQuery,
  DocsSearchResult,
  DocsSearchResultType,
  DocsSearchSourcePage,
  SimpleDocsSearchConfig,
  AlgoliaDocsSearchConfig,
  TypesenseDocsSearchConfig,
  CustomDocsSearchConfig,
  DocsSearchEmbeddingsConfig,
  McpDocsSearchConfig,
  DocsAnalyticsConfig,
  DocsAnalyticsEvent,
  DocsAnalyticsEventInput,
  DocsAnalyticsEventType,
  DocsAnalyticsInput,
  DocsAnalyticsSource,
  DocsCloudApiKeyConfig,
  DocsCloudConfig,
  DocsCloudFeatureConfig,
  DocsCloudPreviewConfig,
  DocsCloudPublishConfig,
  DocsCodeBlocksConfig,
  DocsCodeBlocksPlannerConfig,
  DocsCodeBlocksPlannerProvider,
  DocsCodeBlocksRunnerConfig,
  DocsCodeBlocksRunnerProvider,
  DocsCodeBlocksValidateConfig,
  DocsCodeBlocksValidationMode,
  DocsCodeBlocksValidationPolicy,
  DocsObservabilityConfig,
  DocsObservabilityEvent,
  DocsObservabilityEventInput,
  DocsAgentTraceEventInput,
  DocsAgentTraceEventType,
  DocsAgentTraceStatus,
} from "./types.js";
export type {
  DocsAgentTraceContext,
  ResolvedDocsAnalyticsConfig,
  ResolvedDocsObservabilityConfig,
} from "./analytics.js";
export type { DocsCloudAnalyticsOptions } from "./cloud-analytics.js";
export type { ChangelogEntrySummary, ResolvedChangelogConfig } from "./changelog.js";
export type { ResolvedDocsI18n, DocsPathMatch } from "./i18n.js";
export type { DocsPageStructuredDataInput, DocsStructuredDataBreadcrumb } from "./metadata.js";
export type {
  DocsAgentDiscoverySpecOptions,
  DocsAgentFeedbackDiscoveryConfig,
  DocsLlmsDiscoveryConfig,
  DocsMarkdownPage,
  DocsSkillDocumentOptions,
} from "./agent.js";
