/**
 * Next.js config wrapper for @farming-labs/docs.
 * Handles MDX compilation, frontmatter, syntax highlighting, TOC extraction,
 * and auto-generates mdx-components.tsx + docs layout when missing.
 *
 * @example
 * // next.config.ts — this is all you need:
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs();
 *
 * @example
 * // With existing Next.js config
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs({
 *     images: { remotePatterns: [{ hostname: "example.com" }] },
 *   });
 *
 * @example
 * // Full static export (Cloudflare Pages, etc.) — no server; API route is skipped.
 * // In docs.config set ai.enabled: false and staticExport: true.
 *   export default withDocs({ output: "export" });
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

/** Resolve Next.js App Router directory: prefer src/app when present, else app. */
function getNextAppDir(root: string): string {
  if (existsSync(join(root, "src", "app"))) return "src/app";
  return "app";
}

// @ts-ignore – no types needed at config time
import createMDX from "@next/mdx";

type MdxPluginEntry = string | [name: string, ...options: any[]];

// ─── Auto-generated file templates ──────────────────────────────────

const GENERATED_BANNER = "// Auto-generated by @farming-labs/next — do not edit manually.\n";
const GENERATED_CSS_BANNER = "/* Auto-generated by @farming-labs/next — do not edit manually. */\n";

const MDX_COMPONENTS_TEMPLATE = `\
${GENERATED_BANNER}
import { getMDXComponents } from "@farming-labs/theme/mdx";
import type { MDXComponents } from "mdx/types";
import docsConfig from "@/docs.config";

export function useMDXComponents(components?: MDXComponents): MDXComponents {
  return getMDXComponents(
    {
      ...(docsConfig.components as MDXComponents),
      ...components,
    },
    {
      onCopyClick: docsConfig.onCopyClick,
      theme: docsConfig.theme,
    },
  );
}
`;

const DOCS_LAYOUT_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createNextDocsLayout, createNextDocsMetadata } from "@farming-labs/next/layout";
import "./docs-theme.css";

export const metadata = createNextDocsMetadata(docsConfig);

const DocsLayout = createNextDocsLayout(docsConfig);

export default function Layout({ children }: { children: React.ReactNode }) {
  return <DocsLayout>{children}</DocsLayout>;
}
`;

const DOCS_API_ROUTE_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/theme/api";

export const { GET, POST } = createDocsAPI({
  entry: docsConfig.entry,
  i18n: docsConfig.i18n,
});

export const revalidate = false;
`;

function docsThemeCssTemplate(cssImport: string): string {
  return `\
${GENERATED_CSS_BANNER}
@reference "tailwindcss";
@import "${cssImport}";
`;
}

const API_REFERENCE_ROUTE_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createNextApiReference } from "@farming-labs/next/api-reference";

export const GET = createNextApiReference(docsConfig);

export const revalidate = false;
`;

// ─── Helpers ────────────────────────────────────────────────────────

const FILE_EXTS = ["tsx", "ts", "jsx", "js"];

function hasFile(root: string, baseName: string): boolean {
  return FILE_EXTS.some((ext) => existsSync(join(root, `${baseName}.${ext}`)));
}

function isManagedGeneratedFile(filePath: string): boolean {
  if (!existsSync(filePath)) return false;

  try {
    return readFileSync(filePath, "utf-8").startsWith(GENERATED_BANNER);
  } catch {
    return false;
  }
}

/** Read the docs entry path from docs.config.ts[x] (defaults to "docs"). */
function readDocsEntry(root: string): string {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, "utf-8");
        const match = content.match(/entry\s*:\s*["']([^"']+)["']/);
        if (match) return match[1];
      } catch {
        // fall through to default
      }
    }
  }
  return "docs";
}

/** Read the OG endpoint from docs.config.ts[x] (returns undefined if not set). */
function readOgEndpoint(root: string): string | undefined {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, "utf-8");
        const match = content.match(/endpoint\s*:\s*["']([^"']+)["']/);
        if (match && match[1]) return match[1];
      } catch {
        // fall through
      }
    }
  }
  return undefined;
}

function readApiReferenceConfig(root: string): {
  enabled: boolean;
  path: string;
  routeRoot: string;
} {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (!existsSync(configPath)) continue;

    try {
      const content = readFileSync(configPath, "utf-8");

      const directFalse = content.match(/apiReference\s*:\s*false/);
      if (directFalse) return { enabled: false, path: "api-reference", routeRoot: "api" };

      const directTrue = content.match(/apiReference\s*:\s*true/);
      if (directTrue) return { enabled: true, path: "api-reference", routeRoot: "api" };

      const block = extractObjectLiteral(content, "apiReference");
      if (!block) continue;

      const enabledMatch = block.match(/enabled\s*:\s*(true|false)/);
      const pathMatch = block.match(/path\s*:\s*["']([^"']+)["']/);
      const routeRootMatch = block.match(/routeRoot\s*:\s*["']([^"']+)["']/);

      return {
        enabled: enabledMatch ? enabledMatch[1] !== "false" : true,
        path: pathMatch?.[1]?.replace(/^\/+|\/+$/g, "") || "api-reference",
        routeRoot: routeRootMatch?.[1]?.replace(/^\/+|\/+$/g, "") || "api",
      };
    } catch {
      return { enabled: false, path: "api-reference", routeRoot: "api" };
    }
  }

  return { enabled: false, path: "api-reference", routeRoot: "api" };
}

function extractObjectLiteral(content: string, key: string): string | undefined {
  const keyIndex = content.search(new RegExp(`${key}\\s*:\\s*\\{`));
  if (keyIndex === -1) return undefined;

  const braceStart = content.indexOf("{", keyIndex);
  if (braceStart === -1) return undefined;

  let depth = 0;

  for (let index = braceStart; index < content.length; index += 1) {
    const char = content[index];

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char !== "}") continue;

    depth -= 1;
    if (depth === 0) {
      return content.slice(braceStart + 1, index);
    }
  }

  return undefined;
}

function parseImportSource(content: string, localName: string): string | undefined {
  const importRegex = /import\s+([^;]+?)\s+from\s+["']([^"']+)["'];?/g;

  for (const match of content.matchAll(importRegex)) {
    const clause = match[1]?.trim();
    const source = match[2];

    if (!clause || !source) continue;

    if (clause.startsWith("* as ")) {
      if (clause.slice(5).trim() === localName) return source;
      continue;
    }

    const namedMatch = clause.match(/\{([\s\S]+)\}/);
    if (namedMatch) {
      const entries = namedMatch[1].split(",");
      for (const entry of entries) {
        const part = entry.trim();
        if (!part) continue;

        const aliasMatch = part.match(/^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/);
        const resolvedName = aliasMatch ? aliasMatch[2] : part;
        if (resolvedName === localName) return source;
      }
    }

    const defaultClause = clause.split(",")[0]?.trim();
    if (
      defaultClause &&
      !defaultClause.startsWith("{") &&
      !defaultClause.startsWith("* as ") &&
      defaultClause === localName
    ) {
      return source;
    }
  }

  return undefined;
}

function resolveThemeCssImportPath(
  source: string,
  root: string,
  layoutDir: string,
): string | undefined {
  const builtInThemeCssByModule: Record<string, string> = {
    "@farming-labs/theme": "@farming-labs/theme/default/css",
    "@farming-labs/theme/default": "@farming-labs/theme/default/css",
    "@farming-labs/theme/colorful": "@farming-labs/theme/colorful/css",
    "@farming-labs/theme/darksharp": "@farming-labs/theme/darksharp/css",
    "@farming-labs/theme/pixel-border": "@farming-labs/theme/pixel-border/css",
    "@farming-labs/theme/shiny": "@farming-labs/theme/shiny/css",
    "@farming-labs/theme/darkbold": "@farming-labs/theme/darkbold/css",
    "@farming-labs/theme/greentree": "@farming-labs/theme/greentree/css",
  };

  const builtIn = builtInThemeCssByModule[source];
  if (builtIn) return builtIn;

  let resolvedModulePath: string | undefined;

  if (source.startsWith("@/")) {
    resolvedModulePath = join(root, source.slice(2));
  } else if (source.startsWith("./") || source.startsWith("../")) {
    resolvedModulePath = join(root, source);
  }

  if (!resolvedModulePath) return undefined;

  const cssPath = resolvedModulePath.replace(/\.(tsx?|jsx?|mts|cts)$/i, ".css").replace(/$/, "");
  const normalizedCssPath = /\.(css)$/i.test(cssPath) ? cssPath : `${cssPath}.css`;
  const rel = relative(layoutDir, normalizedCssPath).replaceAll("\\", "/");

  return rel.startsWith(".") ? rel : `./${rel}`;
}

function readThemeCssImport(root: string, layoutDir: string): string {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (!existsSync(configPath)) continue;

    try {
      const content = readFileSync(configPath, "utf-8");
      const themeCall = content.match(/theme\s*:\s*([A-Za-z_$][\w$]*)\s*\(/);
      const themeIdentifier = themeCall?.[1];
      if (!themeIdentifier) continue;

      const source = parseImportSource(content, themeIdentifier);
      if (!source) continue;

      const cssImport = resolveThemeCssImportPath(source, root, layoutDir);
      if (cssImport) return cssImport;
    } catch {
      // fall through to default
    }
  }

  return "@farming-labs/theme/default/css";
}

// ─── withDocs ───────────────────────────────────────────────────────

export function withDocs(nextConfig: Record<string, unknown> = {}) {
  const root = process.cwd();

  // ── 1. Auto-generate mdx-components.tsx if missing ──────────────
  if (!hasFile(root, "mdx-components")) {
    writeFileSync(join(root, "mdx-components.tsx"), MDX_COMPONENTS_TEMPLATE);
  }

  // ── 2. Auto-generate app/{entry}/layout.tsx if missing (or src/app when using src dir) ──
  const entry = readDocsEntry(root);
  const appDir = getNextAppDir(root);
  const layoutDir = join(root, appDir, entry);
  if (!existsSync(layoutDir)) {
    mkdirSync(layoutDir, { recursive: true });
  }

  const docsLayoutPath = join(layoutDir, "layout.tsx");
  if (!hasFile(layoutDir, "layout") || isManagedGeneratedFile(docsLayoutPath)) {
    writeFileSync(join(layoutDir, "layout.tsx"), DOCS_LAYOUT_TEMPLATE);
  }

  const docsThemeCssPath = join(layoutDir, "docs-theme.css");
  writeFileSync(docsThemeCssPath, docsThemeCssTemplate(readThemeCssImport(root, layoutDir)));

  // ── 3. Auto-generate app/api/docs/route.ts if missing (skip for static export) ──
  // With output: 'export' (Cloudflare Pages, etc.) there is no server; set ai.enabled: false
  // and use client-side search or leave search disabled.
  const isStaticExport = nextConfig.output === "export";
  const docsApiRouteDir = join(root, appDir, "api", "docs");
  if (!isStaticExport && !hasFile(docsApiRouteDir, "route")) {
    mkdirSync(docsApiRouteDir, { recursive: true });
    writeFileSync(join(docsApiRouteDir, "route.ts"), DOCS_API_ROUTE_TEMPLATE);
  }

  // ── 3.1. Auto-generate app/{apiReference.path}/[[...slug]]/route.ts ──
  const apiReference = readApiReferenceConfig(root);
  if (apiReference.enabled && !isStaticExport) {
    const apiReferenceRouteDir = join(root, appDir, ...apiReference.path.split("/"), "[[...slug]]");
    if (!hasFile(apiReferenceRouteDir, "route")) {
      mkdirSync(apiReferenceRouteDir, { recursive: true });
      writeFileSync(join(apiReferenceRouteDir, "route.ts"), API_REFERENCE_ROUTE_TEMPLATE);
    }
  }

  // ── 4. Configure MDX compilation ────────────────────────────────
  const ogEndpoint = readOgEndpoint(root);
  const remarkPlugins: MdxPluginEntry[] = ["remark-gfm", "remark-frontmatter"];
  if (ogEndpoint) {
    remarkPlugins.push(["@farming-labs/next/mdx-plugins/remark-og", { endpoint: ogEndpoint }]);
  }
  remarkPlugins.push(
    ["remark-mdx-frontmatter", { name: "metadata" }],
    "@farming-labs/next/mdx-plugins/remark-heading",
  );
  const rehypePlugins: MdxPluginEntry[] = [
    "@farming-labs/next/mdx-plugins/rehype-toc",
    [
      "@farming-labs/next/mdx-plugins/rehype-code",
      { themes: { dark: "github-dark", light: "github-light" } },
    ],
  ];

  const withMDX = createMDX({
    extension: /\.mdx?$/,
    options: {
      remarkPlugins,
      rehypePlugins,
    },
  });

  // ── 5. Ensure pageExtensions includes md/mdx ───────────────────
  const defaultExts = ["js", "jsx", "md", "mdx", "ts", "tsx"];
  const userExts = nextConfig.pageExtensions as string[] | undefined;

  if (userExts) {
    for (const ext of ["md", "mdx"]) {
      if (!userExts.includes(ext)) {
        userExts.push(ext);
      }
    }
  } else {
    nextConfig.pageExtensions = defaultExts;
  }

  return withMDX(nextConfig);
}
