/**
 * Next.js config wrapper for @farming-labs/docs.
 * Handles MDX compilation, frontmatter, syntax highlighting, TOC extraction,
 * and auto-generates mdx-components.tsx + docs layout when missing.
 *
 * @example
 * // next.config.ts — this is all you need:
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs();
 *
 * @example
 * // With existing Next.js config
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs({
 *     images: { remotePatterns: [{ hostname: "example.com" }] },
 *   });
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

// @ts-ignore – no types needed at config time
import createMDX from "@next/mdx";
// @ts-ignore
import remarkFrontmatter from "remark-frontmatter";
// @ts-ignore
import remarkMdxFrontmatter from "remark-mdx-frontmatter";
// @ts-ignore
import rehypePrettyCode from "rehype-pretty-code";
// @ts-ignore
import { remarkHeading, rehypeToc } from "fumadocs-core/mdx-plugins";

// ─── Auto-generated file templates ──────────────────────────────────

const GENERATED_BANNER = "// Auto-generated by @farming-labs/next — do not edit manually.\n";

const MDX_COMPONENTS_TEMPLATE = `\
${GENERATED_BANNER}
import { getMDXComponents } from "@farming-labs/fumadocs/mdx";
import type { MDXComponents } from "mdx/types";
import docsConfig from "@/docs.config";

export function useMDXComponents(components?: MDXComponents): MDXComponents {
  return getMDXComponents({
    ...(docsConfig.components as MDXComponents),
    ...components,
  });
}
`;

const DOCS_LAYOUT_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createDocsLayout, createDocsMetadata } from "@farming-labs/fumadocs";

export const metadata = createDocsMetadata(docsConfig);
export default createDocsLayout(docsConfig);
`;

// ─── Helpers ────────────────────────────────────────────────────────

const FILE_EXTS = ["tsx", "ts", "jsx", "js"];

function hasFile(root: string, baseName: string): boolean {
  return FILE_EXTS.some((ext) => existsSync(join(root, `${baseName}.${ext}`)));
}

/** Read the docs entry path from docs.config.ts[x] (defaults to "docs"). */
function readDocsEntry(root: string): string {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, "utf-8");
        // Match entry: "..." or entry: '...' in the config
        const match = content.match(/entry\s*:\s*["']([^"']+)["']/);
        if (match) return match[1];
      } catch {
        // fall through to default
      }
    }
  }
  return "docs";
}

// ─── withDocs ───────────────────────────────────────────────────────

export function withDocs(nextConfig: Record<string, unknown> = {}) {
  const root = process.cwd();

  // ── 1. Auto-generate mdx-components.tsx if missing ──────────────
  if (!hasFile(root, "mdx-components")) {
    writeFileSync(join(root, "mdx-components.tsx"), MDX_COMPONENTS_TEMPLATE);
  }

  // ── 2. Auto-generate app/{entry}/layout.tsx if missing ──────────
  const entry = readDocsEntry(root);
  const layoutDir = join(root, "app", entry);
  if (existsSync(layoutDir) && !hasFile(layoutDir, "layout")) {
    writeFileSync(join(layoutDir, "layout.tsx"), DOCS_LAYOUT_TEMPLATE);
  } else if (!existsSync(layoutDir)) {
    // Create the directory and layout if the entry folder doesn't exist yet
    mkdirSync(layoutDir, { recursive: true });
    writeFileSync(join(layoutDir, "layout.tsx"), DOCS_LAYOUT_TEMPLATE);
  }

  // ── 3. Configure MDX compilation ────────────────────────────────
  const withMDX = createMDX({
    extension: /\.mdx?$/,
    options: {
      remarkPlugins: [
        remarkFrontmatter,
        // Export frontmatter as `export const metadata = { title, description, ... }`
        // Next.js App Router automatically uses this for page <title> and <meta>.
        [remarkMdxFrontmatter, { name: "metadata" }],
        remarkHeading, // adds id attributes to headings
      ],
      rehypePlugins: [
        rehypeToc, // extracts TOC data and exports as `toc` from each MDX file
        [
          rehypePrettyCode,
          { theme: { dark: "github-dark", light: "github-light" } },
        ],
      ],
    },
  });

  // ── 4. Ensure pageExtensions includes md/mdx ───────────────────
  const defaultExts = ["js", "jsx", "md", "mdx", "ts", "tsx"];
  const userExts = nextConfig.pageExtensions as string[] | undefined;

  if (userExts) {
    for (const ext of ["md", "mdx"]) {
      if (!userExts.includes(ext)) {
        userExts.push(ext);
      }
    }
  } else {
    nextConfig.pageExtensions = defaultExts;
  }

  return withMDX(nextConfig);
}
