/**
 * Next.js config wrapper for @farming-labs/docs.
 * Handles MDX compilation, frontmatter, syntax highlighting, TOC extraction,
 * and auto-generates mdx-components.tsx + docs layout when missing.
 *
 * @example
 * // next.config.ts — this is all you need:
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs();
 *
 * @example
 * // With existing Next.js config
 *   import { withDocs } from "@farming-labs/next/config";
 *   export default withDocs({
 *     images: { remotePatterns: [{ hostname: "example.com" }] },
 *   });
 *
 * @example
 * // Full static export (Cloudflare Pages, etc.) — no server; API route is skipped.
 * // In docs.config set ai.enabled: false and staticExport: true.
 *   export default withDocs({ output: "export" });
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

/** Resolve Next.js App Router directory: prefer src/app when present, else app. */
function getNextAppDir(root: string): string {
  if (existsSync(join(root, "src", "app"))) return "src/app";
  return "app";
}

// @ts-ignore – no types needed at config time
import createMDX from "@next/mdx";

type MdxPluginEntry = string | [name: string, ...options: any[]];

// ─── Auto-generated file templates ──────────────────────────────────

const GENERATED_BANNER = "// Auto-generated by @farming-labs/next — do not edit manually.\n";

const MDX_COMPONENTS_TEMPLATE = `\
${GENERATED_BANNER}
import { getMDXComponents } from "@farming-labs/theme/mdx";
import type { MDXComponents } from "mdx/types";
import docsConfig from "@/docs.config";

export function useMDXComponents(components?: MDXComponents): MDXComponents {
  return getMDXComponents(
    {
      ...(docsConfig.components as MDXComponents),
      ...components,
    },
    {
      onCopyClick: docsConfig.onCopyClick,
      theme: docsConfig.theme,
    },
  );
}
`;

const DOCS_LAYOUT_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createNextDocsLayout, createNextDocsMetadata } from "@farming-labs/next/layout";

export const metadata = createNextDocsMetadata(docsConfig);

const DocsLayout = createNextDocsLayout(docsConfig);

export default function Layout({ children }: { children: React.ReactNode }) {
  return <DocsLayout>{children}</DocsLayout>;
}
`;

const DOCS_API_ROUTE_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/next/api";

export const { GET, POST } = createDocsAPI({
  entry: docsConfig.entry,
  i18n: docsConfig.i18n,
  search: docsConfig.search,
  ai: docsConfig.ai,
});

export const revalidate = false;
`;

const DOCS_MCP_ROUTE_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createDocsMCPAPI } from "@farming-labs/next/api";

export const { GET, POST, DELETE } = createDocsMCPAPI({
  entry: docsConfig.entry,
  contentDir: docsConfig.contentDir,
  nav: docsConfig.nav,
  ordering: docsConfig.ordering,
  search: docsConfig.search,
  mcp: docsConfig.mcp,
});

export const revalidate = false;
`;

const API_REFERENCE_ROUTE_TEMPLATE = `\
${GENERATED_BANNER}
import docsConfig from "@/docs.config";
import { createNextApiReference } from "@farming-labs/next/api-reference";

export const GET = createNextApiReference(docsConfig);

export const revalidate = false;
`;

// ─── Helpers ────────────────────────────────────────────────────────

const FILE_EXTS = ["tsx", "ts", "jsx", "js"];
const INTERNAL_DOCS_CONFIG_ALIAS = "@farming-labs/next-internal-docs-config";

function hasFile(root: string, baseName: string): boolean {
  return FILE_EXTS.some((ext) => existsSync(join(root, `${baseName}.${ext}`)));
}

function isManagedGeneratedFile(filePath: string): boolean {
  if (!existsSync(filePath)) return false;

  try {
    return readFileSync(filePath, "utf-8").startsWith(GENERATED_BANNER);
  } catch {
    return false;
  }
}

/** Read the docs entry path from docs.config.ts[x] (defaults to "docs"). */
function readDocsEntry(root: string): string {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, "utf-8");
        const match = content.match(/entry\s*:\s*["']([^"']+)["']/);
        if (match) return match[1];
      } catch {
        // fall through to default
      }
    }
  }
  return "docs";
}

function readDocsConfigPath(root: string): string {
  for (const ext of FILE_EXTS) {
    const relativePath = `docs.config.${ext}`;
    if (existsSync(join(root, relativePath))) return relativePath;
  }

  return "docs.config.ts";
}

/** Read the OG endpoint from docs.config.ts[x] (returns undefined if not set). */
function readOgEndpoint(root: string): string | undefined {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, "utf-8");
        const match = content.match(/endpoint\s*:\s*["']([^"']+)["']/);
        if (match && match[1]) return match[1];
      } catch {
        // fall through
      }
    }
  }
  return undefined;
}

function readApiReferenceConfig(root: string): {
  enabled: boolean;
  path: string;
  routeRoot: string;
} {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (!existsSync(configPath)) continue;

    try {
      const content = readFileSync(configPath, "utf-8");

      const directFalse = content.match(/apiReference\s*:\s*false/);
      if (directFalse) return { enabled: false, path: "api-reference", routeRoot: "api" };

      const directTrue = content.match(/apiReference\s*:\s*true/);
      if (directTrue) return { enabled: true, path: "api-reference", routeRoot: "api" };

      const block = extractObjectLiteral(content, "apiReference");
      if (!block) continue;

      const enabledMatch = block.match(/enabled\s*:\s*(true|false)/);
      const pathMatch = block.match(/path\s*:\s*["']([^"']+)["']/);
      const routeRootMatch = block.match(/routeRoot\s*:\s*["']([^"']+)["']/);

      return {
        enabled: enabledMatch ? enabledMatch[1] !== "false" : true,
        path: pathMatch?.[1]?.replace(/^\/+|\/+$/g, "") || "api-reference",
        routeRoot: routeRootMatch?.[1]?.replace(/^\/+|\/+$/g, "") || "api",
      };
    } catch {
      return { enabled: false, path: "api-reference", routeRoot: "api" };
    }
  }

  return { enabled: false, path: "api-reference", routeRoot: "api" };
}

function extractObjectLiteral(content: string, key: string): string | undefined {
  const keyIndex = content.search(new RegExp(`${key}\\s*:\\s*\\{`));
  if (keyIndex === -1) return undefined;

  const braceStart = content.indexOf("{", keyIndex);
  if (braceStart === -1) return undefined;

  let depth = 0;

  for (let index = braceStart; index < content.length; index += 1) {
    const char = content[index];

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char !== "}") continue;

    depth -= 1;
    if (depth === 0) {
      return content.slice(braceStart + 1, index);
    }
  }

  return undefined;
}

function readMcpConfig(root: string): {
  enabled: boolean;
  route: string;
} {
  for (const ext of FILE_EXTS) {
    const configPath = join(root, `docs.config.${ext}`);
    if (!existsSync(configPath)) continue;

    try {
      const content = readFileSync(configPath, "utf-8");

      if (content.match(/mcp\s*:\s*false/)) {
        return { enabled: false, route: "/api/docs/mcp" };
      }

      if (content.match(/mcp\s*:\s*true/)) {
        return { enabled: true, route: "/api/docs/mcp" };
      }

      const block = extractObjectLiteral(content, "mcp");
      if (!block) continue;

      const enabledMatch = block.match(/enabled\s*:\s*(true|false)/);
      const routeMatch = block.match(/route\s*:\s*["']([^"']+)["']/);

      return {
        enabled: enabledMatch ? enabledMatch[1] !== "false" : true,
        route: normalizeRoutePath(routeMatch?.[1] ?? "/api/docs/mcp"),
      };
    } catch {
      return { enabled: false, route: "/api/docs/mcp" };
    }
  }

  return { enabled: false, route: "/api/docs/mcp" };
}

function normalizeRoutePath(route: string): string {
  const normalized = `/${route}`.replace(/\/+/g, "/");
  return normalized !== "/" ? normalized.replace(/\/+$/, "") : "/api/docs/mcp";
}

// ─── withDocs ───────────────────────────────────────────────────────

export function withDocs(nextConfig: Record<string, unknown> = {}) {
  const root = process.cwd();
  const docsConfigPath = readDocsConfigPath(root);
  const docsConfigAbsolutePath = join(root, docsConfigPath);
  const docsConfigRelativeAlias =
    docsConfigPath.startsWith("./") || docsConfigPath.startsWith("../")
      ? docsConfigPath
      : `./${docsConfigPath}`;

  // ── 1. Auto-generate mdx-components.tsx if missing ──────────────
  if (!hasFile(root, "mdx-components")) {
    writeFileSync(join(root, "mdx-components.tsx"), MDX_COMPONENTS_TEMPLATE);
  }

  // ── 2. Auto-generate app/{entry}/layout.tsx if missing (or src/app when using src dir) ──
  const entry = readDocsEntry(root);
  const appDir = getNextAppDir(root);
  const layoutDir = join(root, appDir, entry);
  if (!existsSync(layoutDir)) {
    mkdirSync(layoutDir, { recursive: true });
  }

  const docsLayoutPath = join(layoutDir, "layout.tsx");
  if (!hasFile(layoutDir, "layout") || isManagedGeneratedFile(docsLayoutPath)) {
    writeFileSync(join(layoutDir, "layout.tsx"), DOCS_LAYOUT_TEMPLATE);
  }

  // ── 3. Auto-generate app/api/docs/route.ts if missing (skip for static export) ──
  // With output: 'export' (Cloudflare Pages, etc.) there is no server; set ai.enabled: false
  // and use client-side search or leave search disabled.
  const isStaticExport = nextConfig.output === "export";
  const docsApiRouteDir = join(root, appDir, "api", "docs");
  if (!isStaticExport && !hasFile(docsApiRouteDir, "route")) {
    mkdirSync(docsApiRouteDir, { recursive: true });
    writeFileSync(join(docsApiRouteDir, "route.ts"), DOCS_API_ROUTE_TEMPLATE);
  }

  const mcp = readMcpConfig(root);
  const docsMcpRouteDir = join(root, appDir, "api", "docs", "mcp");
  if (
    mcp.enabled &&
    mcp.route === "/api/docs/mcp" &&
    !isStaticExport &&
    !hasFile(docsMcpRouteDir, "route")
  ) {
    mkdirSync(docsMcpRouteDir, { recursive: true });
    writeFileSync(join(docsMcpRouteDir, "route.ts"), DOCS_MCP_ROUTE_TEMPLATE);
  }

  // ── 3.1. Auto-generate app/{apiReference.path}/[[...slug]]/route.ts ──
  const apiReference = readApiReferenceConfig(root);
  if (apiReference.enabled && !isStaticExport) {
    const apiReferenceRouteDir = join(root, appDir, ...apiReference.path.split("/"), "[[...slug]]");
    if (!hasFile(apiReferenceRouteDir, "route")) {
      mkdirSync(apiReferenceRouteDir, { recursive: true });
      writeFileSync(join(apiReferenceRouteDir, "route.ts"), API_REFERENCE_ROUTE_TEMPLATE);
    }
  }

  // ── 4. Configure MDX compilation ────────────────────────────────
  const ogEndpoint = readOgEndpoint(root);
  const remarkPlugins: MdxPluginEntry[] = ["remark-gfm", "remark-frontmatter"];
  if (ogEndpoint) {
    remarkPlugins.push(["@farming-labs/next/mdx-plugins/remark-og", { endpoint: ogEndpoint }]);
  }
  remarkPlugins.push(
    ["remark-mdx-frontmatter", { name: "metadata" }],
    "@farming-labs/next/mdx-plugins/remark-heading",
  );
  const rehypePlugins: MdxPluginEntry[] = [
    "@farming-labs/next/mdx-plugins/rehype-toc",
    [
      "@farming-labs/next/mdx-plugins/rehype-code",
      { themes: { dark: "github-dark", light: "github-light" } },
    ],
  ];

  const withMDX = createMDX({
    extension: /\.mdx?$/,
    options: {
      remarkPlugins,
      rehypePlugins,
    },
  });

  // ── 5. Ensure pageExtensions includes md/mdx ───────────────────
  const defaultExts = ["js", "jsx", "md", "mdx", "ts", "tsx"];
  const userExts = nextConfig.pageExtensions as string[] | undefined;

  if (userExts) {
    for (const ext of ["md", "mdx"]) {
      if (!userExts.includes(ext)) {
        userExts.push(ext);
      }
    }
  } else {
    nextConfig.pageExtensions = defaultExts;
  }

  const existingTurbopack = (nextConfig.turbopack as Record<string, unknown> | undefined) ?? {};
  const existingResolveAlias =
    (existingTurbopack.resolveAlias as Record<string, string> | undefined) ?? {};

  nextConfig.turbopack = {
    ...existingTurbopack,
    resolveAlias: {
      ...existingResolveAlias,
      [INTERNAL_DOCS_CONFIG_ALIAS]: docsConfigRelativeAlias,
    },
  };

  const userWebpack = nextConfig.webpack as
    | ((config: Record<string, any>, options: Record<string, any>) => Record<string, any>)
    | undefined;

  nextConfig.webpack = (config: Record<string, any>, options: Record<string, any>) => {
    const resolvedConfig = userWebpack ? userWebpack(config, options) : config;
    resolvedConfig.resolve ??= {};
    resolvedConfig.resolve.alias ??= {};
    resolvedConfig.resolve.alias[INTERNAL_DOCS_CONFIG_ALIAS] = docsConfigAbsolutePath;
    return resolvedConfig;
  };

  return withMDX(nextConfig);
}
