// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/docs" | "/docs/authentication" | "/docs/authentication/email-verification" | "/docs/authentication/social-sign-on" | "/docs/basic-usage" | "/docs/concepts" | "/docs/concepts/database" | "/docs/concepts/session-management" | "/docs/create-content" | "/docs/create-content/code-blocks" | "/docs/create-content/format-text" | "/docs/create-content/images-embeds" | "/docs/customize" | "/docs/customize/custom-404" | "/docs/customize/custom-domain" | "/docs/customize/custom-scripts" | "/docs/customize/fonts" | "/docs/customize/react-components" | "/docs/customize/themes" | "/docs/en" | "/docs/en/getting-started" | "/docs/en/installation" | "/docs/fr" | "/docs/fr/getting-started" | "/docs/fr/installation" | "/docs/getting-started" | "/docs/getting-started/ai-native" | "/docs/getting-started/migration-guide" | "/docs/getting-started/quickstart" | "/docs/installation" | "/docs/integrations" | "/docs/organize" | "/docs/organize/exclude-files" | "/docs/organize/global-settings" | "/docs/organize/hidden-pages" | "/docs/organize/navigation" | "/docs/organize/pages" | "/docs/plugins" | "/docs/plugins/organizations" | "/docs/plugins/two-factor" | "/docs/quickstart" | "/docs/reference"
type AppRouteHandlerRoutes = "/api/docs" | "/api/og" | "/api/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/docs"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/docs": {}
  "/api/og": {}
  "/api/search": {}
  "/docs": {}
  "/docs/authentication": {}
  "/docs/authentication/email-verification": {}
  "/docs/authentication/social-sign-on": {}
  "/docs/basic-usage": {}
  "/docs/concepts": {}
  "/docs/concepts/database": {}
  "/docs/concepts/session-management": {}
  "/docs/create-content": {}
  "/docs/create-content/code-blocks": {}
  "/docs/create-content/format-text": {}
  "/docs/create-content/images-embeds": {}
  "/docs/customize": {}
  "/docs/customize/custom-404": {}
  "/docs/customize/custom-domain": {}
  "/docs/customize/custom-scripts": {}
  "/docs/customize/fonts": {}
  "/docs/customize/react-components": {}
  "/docs/customize/themes": {}
  "/docs/en": {}
  "/docs/en/getting-started": {}
  "/docs/en/installation": {}
  "/docs/fr": {}
  "/docs/fr/getting-started": {}
  "/docs/fr/installation": {}
  "/docs/getting-started": {}
  "/docs/getting-started/ai-native": {}
  "/docs/getting-started/migration-guide": {}
  "/docs/getting-started/quickstart": {}
  "/docs/installation": {}
  "/docs/integrations": {}
  "/docs/organize": {}
  "/docs/organize/exclude-files": {}
  "/docs/organize/global-settings": {}
  "/docs/organize/hidden-pages": {}
  "/docs/organize/navigation": {}
  "/docs/organize/pages": {}
  "/docs/plugins": {}
  "/docs/plugins/organizations": {}
  "/docs/plugins/two-factor": {}
  "/docs/quickstart": {}
  "/docs/reference": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/docs": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
