import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import pc from "picocolors";
import {
  DEFAULT_AGENT_MD_ROUTE,
  DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE,
  DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE,
  DEFAULT_AGENTS_MD_ROUTE,
  DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
  DEFAULT_LLMS_FULL_TXT_ROUTE,
  DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE,
  DEFAULT_LLMS_TXT_ROUTE,
  DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE,
  DEFAULT_SKILL_MD_ROUTE,
  DEFAULT_SKILL_MD_WELL_KNOWN_ROUTE,
  buildDocsAgentDiscoverySpec,
  renderDocsAgentsDocument,
  renderDocsLlmsTxt,
  renderDocsMarkdownDocument,
  renderDocsSkillDocument,
  resolveDocsAgentFeedbackConfig,
  toDocsMarkdownUrl,
  type DocsLlmsDiscoveryConfig,
} from "../agent.js";
import { resolveApiReferenceOpenApiDiscovery } from "../api-reference.js";
import { resolveDocsI18n } from "../i18n.js";
import type { DocsMcpPage, DocsMcpResolvedConfig } from "../mcp.js";
import {
  DOCS_ROBOTS_GENERATED_BLOCK_END,
  DOCS_ROBOTS_GENERATED_BLOCK_START,
  renderDocsRobotsGeneratedBlock,
  resolveDocsRobotsConfig,
  upsertDocsRobotsGeneratedBlock,
} from "../robots.js";
import {
  buildDocsSitemapManifest,
  renderDocsSitemapMarkdown,
  renderDocsSitemapXml,
  resolveDocsSitemapConfig,
  type DocsSitemapManifest,
} from "../sitemap.js";
import { createFilesystemDocsMcpSource, resolveDocsMcpConfig } from "../server.js";
import type {
  DocsConfig,
  DocsI18nConfig,
  DocsMcpConfig,
  DocsRobotsConfig,
  DocsSitemapConfig,
  LlmsTxtConfig,
} from "../types.js";
import {
  extractNestedObjectLiteral,
  extractTopLevelConfigObject,
  loadDocsConfigModule,
  readBooleanProperty,
  readNavTitle,
  readStringProperty,
  readTopLevelBooleanProperty,
  readTopLevelStringProperty,
  resolveDocsConfigPath,
  resolveDocsContentDir,
} from "./config.js";
import { detectFramework } from "./utils.js";

export interface AgentExportOptions {
  configPath?: string;
  public?: boolean;
  check?: boolean;
}

export interface ParsedAgentExportArgs extends AgentExportOptions {
  help?: boolean;
}

type AgentBundleFileKind =
  | "page"
  | "llms"
  | "discovery"
  | "skill"
  | "agents"
  | "sitemap"
  | "robots";

export interface AgentBundleManifestFile {
  path: string;
  route: string;
  kind: AgentBundleFileKind;
  mediaType: string;
  bytes: number;
  sha256: string;
  managed: boolean;
}

export interface AgentBundleManifestPage {
  route: string;
  markdownRoute: string;
  sourcePath?: string;
  locale?: string;
}

export interface AgentBundleManifestInternalFile {
  path: string;
  kind: "sitemap";
  bytes: number;
  sha256: string;
}

export interface AgentBundleManifest {
  format: "farming-labs-agent-bundle.v1";
  generator: "@farming-labs/docs";
  entry: string;
  publicDirectory: "public" | "static";
  baseUrl?: string;
  contentHash: string;
  files: AgentBundleManifestFile[];
  internalFiles: AgentBundleManifestInternalFile[];
  pages: AgentBundleManifestPage[];
}

interface LocalizedPage {
  page: DocsMcpPage;
  locale?: string;
}

interface PlannedOutput {
  absolutePath: string;
  publicPath: string;
  route: string;
  kind: AgentBundleFileKind;
  mediaType: string;
  content: string;
  managed: boolean;
}

interface PlannedInternalOutput {
  absolutePath: string;
  path: string;
  kind: "sitemap";
  content: string;
}

const AGENT_EXPORT_AGENTS_MARKER = "<!-- Generated by @farming-labs/docs agent export. -->";
const AGENTS_GENERATE_MARKER = "<!-- Generated by @farming-labs/docs agents generate. -->";
const AGENT_BUNDLE_MANIFEST_ROUTE = "/.well-known/agent-bundle.json";
const AGENT_BUNDLE_INTERNAL_MANIFEST = ".farming-labs/agent-bundle-manifest.json";
const SKILL_CANONICAL_ROUTE = "/skills/docs/SKILL.md";

function parseInlineFlag(arg: string): { key: string; value?: string } {
  const [rawKey, value] = arg.slice(2).split("=", 2);
  return { key: rawKey.trim(), value };
}

export function parseAgentExportArgs(argv: string[]): ParsedAgentExportArgs {
  const parsed: ParsedAgentExportArgs = {};

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--help" || arg === "-h") {
      parsed.help = true;
      continue;
    }

    if (arg === "--public") {
      parsed.public = true;
      continue;
    }

    if (arg === "--check") {
      parsed.check = true;
      continue;
    }

    if (arg.startsWith("--config=")) {
      const value = parseInlineFlag(arg).value;
      if (!value) throw new Error("Missing value for --config.");
      parsed.configPath = value;
      continue;
    }

    if (arg === "--config") {
      const value = argv[index + 1];
      if (!value || value.startsWith("--")) throw new Error("Missing value for --config.");
      parsed.configPath = value;
      index += 1;
      continue;
    }

    throw new Error(`Unknown agent export flag: ${arg}.`);
  }

  return parsed;
}

function normalizePathSegment(value: string): string {
  return value.replace(/^\/+|\/+$/g, "");
}

function normalizeContent(content: string): string {
  return `${content.trimEnd()}\n`;
}

function publicFilePath(publicDir: string, route: string): string {
  const resolved = resolveContainedPath(publicDir, route.replace(/^\/+/, ""));
  if (!resolved)
    throw new Error(`Agent Bundle route must stay inside the public directory: ${route}`);
  return resolved;
}

function publicRelativePath(publicDir: string, filePath: string): string {
  return path.relative(publicDir, filePath).replace(/\\/g, "/");
}

function resolveContainedPath(baseDir: string, relativePath: string): string | undefined {
  const base = path.resolve(baseDir);
  const resolved = path.resolve(base, relativePath);
  return resolved.startsWith(`${base}${path.sep}`) ? resolved : undefined;
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function byteLength(content: string): number {
  return Buffer.byteLength(content, "utf-8");
}

function readExisting(filePath: string): string | undefined {
  return existsSync(filePath) ? readFileSync(filePath, "utf-8") : undefined;
}

function atomicWriteFile(filePath: string, content: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporaryPath, content, "utf-8");
    renameSync(temporaryPath, filePath);
  } finally {
    if (existsSync(temporaryPath)) rmSync(temporaryPath, { force: true });
  }
}

function readStaticLlmsConfig(content: string): boolean | LlmsTxtConfig | undefined {
  const enabled = readTopLevelBooleanProperty(content, "llmsTxt");
  if (enabled !== undefined) return enabled;

  const block = extractNestedObjectLiteral(content, ["llmsTxt"]);
  if (!block) return undefined;
  const maxCharsBlock = extractNestedObjectLiteral(content, ["llmsTxt", "maxChars"]);
  return {
    enabled: readBooleanProperty(block, "enabled") ?? true,
    baseUrl: readStringProperty(block, "baseUrl"),
    siteTitle: readStringProperty(block, "siteTitle"),
    siteDescription: readStringProperty(block, "siteDescription"),
    maxChars: maxCharsBlock
      ? {
          mode: readStringProperty(maxCharsBlock, "mode") as "warn" | "error" | "off" | undefined,
          chars: readNumericProperty(maxCharsBlock, "chars"),
        }
      : undefined,
    sections: readStaticLlmsSections(block),
  };
}

function readNumericProperty(content: string, key: string): number | undefined {
  const match = content.match(new RegExp(`\\b${key}\\b\\s*:\\s*(-?\\d[\\d_]*(?:\\.\\d+)?)`));
  if (!match) return undefined;
  const value = Number(match[1].replace(/_/g, ""));
  return Number.isFinite(value) ? value : undefined;
}

function findBalancedDelimiterEnd(
  content: string,
  start: number,
  open: "[" | "{",
  close: "]" | "}",
): number {
  let depth = 0;
  let quote: '"' | "'" | "`" | null = null;
  let escaped = false;

  for (let index = start; index < content.length; index += 1) {
    const char = content[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === quote) quote = null;
      continue;
    }
    if (char === '"' || char === "'" || char === "`") {
      quote = char;
      continue;
    }
    if (char === open) depth += 1;
    if (char !== close) continue;
    depth -= 1;
    if (depth === 0) return index;
  }
  return -1;
}

function extractArrayProperty(content: string, key: string): string | undefined {
  const keyIndex = content.search(new RegExp(`\\b${key}\\b\\s*:\\s*\\[`));
  if (keyIndex === -1) return undefined;
  const start = content.indexOf("[", keyIndex);
  if (start === -1) return undefined;
  const end = findBalancedDelimiterEnd(content, start, "[", "]");
  return end === -1 ? undefined : content.slice(start + 1, end);
}

function readStaticLlmsSections(content: string): LlmsTxtConfig["sections"] {
  const sections = extractArrayProperty(content, "sections");
  if (!sections) return undefined;
  const result: NonNullable<LlmsTxtConfig["sections"]> = [];

  for (let index = 0; index < sections.length; index += 1) {
    if (sections[index] !== "{") continue;
    const end = findBalancedDelimiterEnd(sections, index, "{", "}");
    if (end === -1) break;
    const block = sections.slice(index + 1, end);
    const title = readStringProperty(block, "title");
    const match = readStringProperty(block, "match") ?? readStringArrayProperty(block, "match");
    if (title && (typeof match === "string" || match.length > 0)) {
      const maxCharsBlock = extractNestedObjectLiteral(block, ["maxChars"]);
      result.push({
        title,
        description: readStringProperty(block, "description"),
        match,
        maxChars: maxCharsBlock
          ? {
              mode: readStringProperty(maxCharsBlock, "mode") as
                | "warn"
                | "error"
                | "off"
                | undefined,
              chars: readNumericProperty(maxCharsBlock, "chars"),
            }
          : undefined,
      });
    }
    index = end;
  }

  return result.length > 0 ? result : undefined;
}

function readStaticSitemapConfig(content: string): boolean | DocsSitemapConfig | undefined {
  const enabled = readTopLevelBooleanProperty(content, "sitemap");
  if (enabled !== undefined) return enabled;

  const block = extractNestedObjectLiteral(content, ["sitemap"]);
  if (!block) return undefined;
  const xmlBoolean = readTopLevelBooleanProperty(block, "xml");
  const xmlBlock = extractNestedObjectLiteral(content, ["sitemap", "xml"]);
  const markdownBoolean = readTopLevelBooleanProperty(block, "markdown");
  const markdownBlock = extractNestedObjectLiteral(content, ["sitemap", "markdown"]);
  return {
    enabled: readBooleanProperty(block, "enabled") ?? true,
    routePrefix: readStringProperty(block, "routePrefix"),
    baseUrl: readStringProperty(block, "baseUrl"),
    manifestPath: readStringProperty(block, "manifestPath"),
    xml:
      xmlBoolean ??
      (xmlBlock
        ? {
            enabled: readBooleanProperty(xmlBlock, "enabled"),
            includeLastmod: readBooleanProperty(xmlBlock, "includeLastmod"),
          }
        : undefined),
    markdown:
      markdownBoolean ??
      (markdownBlock
        ? {
            enabled: readBooleanProperty(markdownBlock, "enabled"),
            includeDescriptions: readBooleanProperty(markdownBlock, "includeDescriptions"),
            includeLastmod: readBooleanProperty(markdownBlock, "includeLastmod"),
            linkTarget: readStringProperty(markdownBlock, "linkTarget") as
              | "html"
              | "markdown"
              | "both"
              | undefined,
          }
        : undefined),
  };
}

function readStaticRobotsConfig(content: string): boolean | DocsRobotsConfig | undefined {
  const enabled = readTopLevelBooleanProperty(content, "robots");
  if (enabled !== undefined) return enabled;

  const block = extractNestedObjectLiteral(content, ["robots"]);
  if (!block) return undefined;
  const ai = readStringProperty(block, "ai");
  return {
    enabled: readBooleanProperty(block, "enabled") ?? true,
    baseUrl: readStringProperty(block, "baseUrl"),
    ai: ai === "allow" || ai === "disallow" ? ai : readBooleanProperty(block, "ai"),
  };
}

function readStaticMcpConfig(content: string): boolean | DocsMcpConfig | undefined {
  const enabled = readTopLevelBooleanProperty(content, "mcp");
  if (enabled !== undefined) return enabled;

  const block = extractNestedObjectLiteral(content, ["mcp"]);
  if (!block) return undefined;
  return {
    enabled: readBooleanProperty(block, "enabled") ?? true,
    route: readStringProperty(block, "route"),
    name: readStringProperty(block, "name"),
    version: readStringProperty(block, "version"),
  };
}

function readStringArrayProperty(content: string, key: string): string[] {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = content.match(new RegExp(`\\b${escaped}\\b\\s*:\\s*\\[([\\s\\S]*?)\\]`));
  if (!match) return [];
  return [...match[1].matchAll(/["']([^"']+)["']/g)].map((value) => value[1]);
}

function readStaticI18nConfig(content: string): DocsI18nConfig | undefined {
  const block = extractNestedObjectLiteral(content, ["i18n"]);
  if (!block) return undefined;
  const locales = readStringArrayProperty(block, "locales");
  if (locales.length === 0) return undefined;
  return {
    locales,
    defaultLocale: readStringProperty(block, "defaultLocale"),
  };
}

function readStaticMetadataDescription(content: string): string | undefined {
  const block = extractNestedObjectLiteral(content, ["metadata"]);
  return block ? readStringProperty(block, "description") : undefined;
}

function readStaticDocsPath(content: string): string | undefined {
  const configured = readTopLevelStringProperty(content, "docsPath");
  if (configured !== undefined) return configured;
  const root = extractTopLevelConfigObject(content) ?? content;
  return /\bdocsPath\b\s*:\s*(["'])\1/.test(root) ? "" : undefined;
}

function readStaticApiReferenceEnabled(content: string): boolean | undefined {
  const value = readTopLevelBooleanProperty(content, "apiReference");
  if (value !== undefined) return value;
  const block = extractNestedObjectLiteral(content, ["apiReference"]);
  return block ? (readBooleanProperty(block, "enabled") ?? true) : undefined;
}

function buildPageUrl(routeEntry: string, slug: string, locale?: string): string {
  const parts = [routeEntry, locale, slug].flatMap((value) =>
    value ? [normalizePathSegment(value)] : [],
  );
  return parts.length > 0 ? `/${parts.join("/")}` : "/";
}

function staticMarkdownRoute(page: DocsMcpPage, sourceEntry: string, routeEntry: string): string {
  if (!routeEntry && !page.slug) return `/${sourceEntry || "docs"}.md`;
  return toDocsMarkdownUrl(page.url);
}

async function loadPages(options: {
  rootDir: string;
  contentDir: string;
  routeEntry: string;
  siteTitle: string;
  ordering: DocsConfig["ordering"];
  i18n: ReturnType<typeof resolveDocsI18n>;
}): Promise<LocalizedPage[]> {
  const localeInputs = options.i18n
    ? options.i18n.locales.map((locale) => ({
        locale,
        directory: path.join(options.contentDir, locale),
      }))
    : [{ locale: undefined, directory: options.contentDir }];
  const pages: LocalizedPage[] = [];

  for (const input of localeInputs) {
    const source = createFilesystemDocsMcpSource({
      rootDir: options.rootDir,
      entry: options.routeEntry || "docs",
      contentDir: input.directory,
      siteTitle: options.siteTitle,
      ordering: options.ordering,
    });
    const scanned = await Promise.resolve(source.getPages());
    const localeRoute =
      input.locale && input.locale !== options.i18n?.defaultLocale ? input.locale : undefined;
    for (const page of scanned) {
      pages.push({
        locale: input.locale,
        page: {
          ...page,
          url: buildPageUrl(options.routeEntry, page.slug, localeRoute),
        },
      });
    }
  }

  return pages;
}

function formatDateOnly(value: string): string | undefined {
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return undefined;
  return parsed.toISOString().slice(0, 10);
}

function pageLastmod(rootDir: string, page: DocsMcpPage) {
  if (page.sourcePath) {
    try {
      const output = execFileSync("git", ["log", "-1", "--format=%cI", "--", page.sourcePath], {
        cwd: rootDir,
        encoding: "utf-8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      const lastmod = formatDateOnly(output);
      if (lastmod) return { lastmod, lastmodSource: "git" as const };
    } catch {
      // Fall back to the file timestamp below.
    }

    const fullPath = path.resolve(rootDir, page.sourcePath);
    if (existsSync(fullPath)) {
      try {
        return {
          lastmod: statSync(fullPath).mtime.toISOString().slice(0, 10),
          lastmodSource: "filesystem" as const,
        };
      } catch {
        // Leave lastmod unset when neither git nor the filesystem can resolve it.
      }
    }
  }

  return undefined;
}

function deterministicSitemapManifest(options: {
  rootDir: string;
  pages: Array<DocsMcpPage & { markdownUrl?: string }>;
  entry: string;
  siteTitle: string;
  baseUrl?: string;
}): DocsSitemapManifest {
  const manifest = buildDocsSitemapManifest({
    pages: options.pages,
    entry: options.entry,
    siteTitle: options.siteTitle,
    baseUrl: options.baseUrl,
    generatedAt: "1970-01-01T00:00:00.000Z",
    resolveLastmod(page) {
      return pageLastmod(options.rootDir, page as DocsMcpPage);
    },
  });
  const newest = manifest.pages.reduce<string | undefined>((current, page) => {
    if (!page.lastmod) return current;
    return !current || page.lastmod > current ? page.lastmod : current;
  }, undefined);
  manifest.generatedAt = `${newest ?? "1970-01-01"}T00:00:00.000Z`;
  return manifest;
}

function isManagedAgentsContent(content: string): boolean {
  return content.includes(AGENT_EXPORT_AGENTS_MARKER) || content.includes(AGENTS_GENERATE_MARKER);
}

function findPublicAgentsSource(publicDir: string): string | undefined {
  for (const route of [
    DEFAULT_AGENTS_MD_ROUTE,
    DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
    DEFAULT_AGENT_MD_ROUTE,
    DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  ]) {
    const content = readExisting(publicFilePath(publicDir, route));
    if (content !== undefined && !isManagedAgentsContent(content)) return normalizeContent(content);
  }
  return undefined;
}

function addOutput(
  outputs: PlannedOutput[],
  publicDir: string,
  route: string,
  kind: AgentBundleFileKind,
  mediaType: string,
  content: string,
  managed = true,
): void {
  const absolutePath = publicFilePath(publicDir, route);
  const collision = outputs.find((output) => output.absolutePath === absolutePath);
  if (collision) {
    throw new Error(
      `Agent Bundle output collision at ${route} (${collision.kind} and ${kind}). Change the conflicting docs slug or configured route.`,
    );
  }
  outputs.push({
    absolutePath,
    publicPath: publicRelativePath(publicDir, absolutePath),
    route,
    kind,
    mediaType,
    content: normalizeContent(content),
    managed,
  });
}

function resolveUserOwnedAgentsOutputs(outputs: PlannedOutput[]): PlannedOutput[] {
  return outputs.map((output) => {
    if (output.kind !== "agents") return output;
    const current = readExisting(output.absolutePath);
    if (current === undefined || isManagedAgentsContent(current)) return output;
    return { ...output, content: normalizeContent(current), managed: false };
  });
}

function resolveUserOwnedOverrides(
  outputs: PlannedOutput[],
  previous: AgentBundleManifest | undefined,
): PlannedOutput[] {
  const preserveKinds = new Set<AgentBundleFileKind>(["page", "llms", "discovery", "skill"]);
  const previousByPath = new Map(previous?.files.map((file) => [file.path, file] as const) ?? []);

  return outputs.map((output) => {
    if (!preserveKinds.has(output.kind)) return output;
    const current = readExisting(output.absolutePath);
    if (current === undefined || current === output.content) return output;
    const previousFile = previousByPath.get(output.publicPath);
    if (previousFile?.managed && sha256(current) === previousFile.sha256) return output;
    return { ...output, content: normalizeContent(current), managed: false };
  });
}

function resolveRobotsOutput(
  publicDir: string,
  entry: string,
  sitemap: boolean | DocsSitemapConfig,
  robots: DocsRobotsConfig,
): PlannedOutput {
  const route = "/robots.txt";
  const absolutePath = publicFilePath(publicDir, route);
  const existing = readExisting(absolutePath);
  const generatedBlock = renderDocsRobotsGeneratedBlock({
    entry,
    sitemap,
    baseUrl: robots.baseUrl,
    robots,
  });
  const hasManagedBlock =
    existing?.includes(DOCS_ROBOTS_GENERATED_BLOCK_START) === true &&
    existing.includes(DOCS_ROBOTS_GENERATED_BLOCK_END);

  if (existing !== undefined && !hasManagedBlock) {
    return {
      absolutePath,
      publicPath: publicRelativePath(publicDir, absolutePath),
      route,
      kind: "robots",
      mediaType: "text/plain",
      content: normalizeContent(existing),
      managed: false,
    };
  }

  return {
    absolutePath,
    publicPath: publicRelativePath(publicDir, absolutePath),
    route,
    kind: "robots",
    mediaType: "text/plain",
    content: normalizeContent(
      existing && hasManagedBlock
        ? upsertDocsRobotsGeneratedBlock(existing, generatedBlock)
        : generatedBlock,
    ),
    managed: true,
  };
}

function toManifestFile(output: PlannedOutput): AgentBundleManifestFile {
  return {
    path: output.publicPath,
    route: output.route,
    kind: output.kind,
    mediaType: output.mediaType,
    bytes: byteLength(output.content),
    sha256: sha256(output.content),
    managed: output.managed,
  };
}

function buildAgentBundleManifest(options: {
  sourceEntry: string;
  entry: string;
  publicDirectory: "public" | "static";
  baseUrl?: string;
  outputs: PlannedOutput[];
  internalOutputs: PlannedInternalOutput[];
  pages: LocalizedPage[];
}): AgentBundleManifest {
  const files = options.outputs
    .map(toManifestFile)
    .sort((left, right) => left.path.localeCompare(right.path));
  const internalFiles = options.internalOutputs
    .map((output) => ({
      path: output.path,
      kind: output.kind,
      bytes: byteLength(output.content),
      sha256: sha256(output.content),
    }))
    .sort((left, right) => left.path.localeCompare(right.path));
  const contentHash = sha256(
    [
      ...files.map((file) => `public:${file.path}\0${file.sha256}`),
      ...internalFiles.map((file) => `internal:${file.path}\0${file.sha256}`),
    ].join("\n"),
  );
  return {
    format: "farming-labs-agent-bundle.v1",
    generator: "@farming-labs/docs",
    entry: options.entry,
    publicDirectory: options.publicDirectory,
    baseUrl: options.baseUrl,
    contentHash,
    files,
    internalFiles,
    pages: options.pages
      .map(({ page, locale }) => ({
        route: page.url,
        markdownRoute: staticMarkdownRoute(page, options.sourceEntry, options.entry),
        sourcePath: page.sourcePath,
        locale,
      }))
      .sort((left, right) => left.markdownRoute.localeCompare(right.markdownRoute)),
  };
}

function readPreviousManifest(rootDir: string): AgentBundleManifest | undefined {
  const manifestPath = path.join(rootDir, AGENT_BUNDLE_INTERNAL_MANIFEST);
  if (!existsSync(manifestPath)) return undefined;
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as AgentBundleManifest;
    if (
      manifest.format !== "farming-labs-agent-bundle.v1" ||
      !Array.isArray(manifest.files) ||
      !Array.isArray(manifest.pages)
    ) {
      return undefined;
    }
    return {
      ...manifest,
      files: manifest.files.filter(
        (file) =>
          file &&
          typeof file.path === "string" &&
          typeof file.sha256 === "string" &&
          typeof file.managed === "boolean",
      ),
      internalFiles: Array.isArray(manifest.internalFiles)
        ? manifest.internalFiles.filter(
            (file) => file && typeof file.path === "string" && typeof file.sha256 === "string",
          )
        : [],
    };
  } catch {
    return undefined;
  }
}

function staleManagedPaths(
  publicDir: string,
  previous: AgentBundleManifest | undefined,
  outputs: PlannedOutput[],
): string[] {
  if (!previous) return [];
  const expected = new Set(outputs.map((output) => output.publicPath));
  return previous.files
    .filter((file) => file.managed && !expected.has(file.path))
    .flatMap((file) => {
      const resolved = resolveContainedPath(publicDir, file.path);
      return resolved ? [resolved] : [];
    })
    .filter((filePath) => existsSync(filePath));
}

function staleInternalPaths(
  rootDir: string,
  previous: AgentBundleManifest | undefined,
  outputs: PlannedInternalOutput[],
): string[] {
  if (!previous?.internalFiles) return [];
  const expected = new Set(outputs.map((output) => output.path));
  return previous.internalFiles
    .filter((file) => !expected.has(file.path))
    .flatMap((file) => {
      const resolved = resolveContainedPath(rootDir, file.path);
      return resolved ? [resolved] : [];
    })
    .filter((filePath) => existsSync(filePath));
}

function removeStaleManagedFiles(
  publicDir: string,
  previous: AgentBundleManifest | undefined,
  stalePaths: string[],
): string[] {
  if (!previous) return [];
  const removed: string[] = [];
  const previousByPath = new Map(
    previous.files.flatMap((file) => {
      const resolved = resolveContainedPath(publicDir, file.path);
      return resolved ? ([[resolved, file]] as const) : [];
    }),
  );
  for (const filePath of stalePaths) {
    const previousFile = previousByPath.get(filePath);
    const current = readExisting(filePath);
    if (!previousFile || current === undefined || sha256(current) !== previousFile.sha256) continue;
    rmSync(filePath);
    removed.push(filePath);
  }
  return removed;
}

function removeStaleInternalFiles(
  rootDir: string,
  previous: AgentBundleManifest | undefined,
  stalePaths: string[],
): string[] {
  if (!previous?.internalFiles) return [];
  const previousByPath = new Map(
    previous.internalFiles.flatMap((file) => {
      const resolved = resolveContainedPath(rootDir, file.path);
      return resolved ? ([[resolved, file]] as const) : [];
    }),
  );
  const removed: string[] = [];
  for (const filePath of stalePaths) {
    const previousFile = previousByPath.get(filePath);
    const current = readExisting(filePath);
    if (!previousFile || current === undefined || sha256(current) !== previousFile.sha256) continue;
    rmSync(filePath);
    removed.push(filePath);
  }
  return removed;
}

function changedOutputs(outputs: PlannedOutput[]): PlannedOutput[] {
  return outputs.filter((output) => readExisting(output.absolutePath) !== output.content);
}

export async function exportAgentBundle(options: AgentExportOptions = {}): Promise<void> {
  if (!options.public && !options.check) {
    throw new Error(
      "Pass --public to write the static Agent Bundle into the framework public directory.",
    );
  }

  const rootDir = process.cwd();
  const loadedConfigModule = await loadDocsConfigModule(rootDir, options.configPath);
  const configPath = loadedConfigModule?.path ?? resolveDocsConfigPath(rootDir, options.configPath);
  const configContent = readFileSync(configPath, "utf-8");
  const config = loadedConfigModule?.config;
  const sourceEntry = normalizePathSegment(
    config?.entry ?? readTopLevelStringProperty(configContent, "entry") ?? "docs",
  );
  const routeEntry = normalizePathSegment(
    config?.docsPath ?? readStaticDocsPath(configContent) ?? sourceEntry,
  );
  const contentDir =
    config?.contentDir ?? resolveDocsContentDir(rootDir, configContent, sourceEntry || "docs");
  const siteTitle =
    typeof config?.nav?.title === "string"
      ? config.nav.title
      : (readNavTitle(configContent) ?? "Documentation");
  const metadataDescription =
    config?.metadata?.description ?? readStaticMetadataDescription(configContent);
  const llmsInput = config?.llmsTxt ?? readStaticLlmsConfig(configContent) ?? true;
  const llmsConfig = typeof llmsInput === "object" ? llmsInput : undefined;
  const llmsEnabled =
    llmsInput !== false && !(typeof llmsInput === "object" && llmsInput.enabled === false);
  const siteDescription = llmsConfig?.siteDescription ?? metadataDescription;
  const resolvedSiteTitle = llmsConfig?.siteTitle ?? siteTitle;
  const sitemapInput = config?.sitemap ?? readStaticSitemapConfig(configContent) ?? true;
  const baseUrl =
    llmsConfig?.baseUrl ?? (typeof sitemapInput === "object" ? sitemapInput.baseUrl : undefined);
  const robotsInput = config?.robots ?? readStaticRobotsConfig(configContent) ?? true;
  const mcpInput = config?.mcp ?? readStaticMcpConfig(configContent);
  const staticExport =
    config?.staticExport ?? readTopLevelBooleanProperty(configContent, "staticExport") ?? false;
  const i18n = resolveDocsI18n(config?.i18n ?? readStaticI18nConfig(configContent));
  const framework = detectFramework(rootDir);
  const publicDirectory = framework === "sveltekit" ? "static" : "public";
  const publicDir = path.join(rootDir, publicDirectory);
  const previous = readPreviousManifest(rootDir);
  const localizedPages = await loadPages({
    rootDir,
    contentDir,
    routeEntry,
    siteTitle: resolvedSiteTitle,
    ordering: config?.ordering,
    i18n,
  });
  if (localizedPages.length === 0) {
    throw new Error(`No docs content was found under ${contentDir}.`);
  }
  const pages = localizedPages.map(({ page }) => page);
  const sitemap = resolveDocsSitemapConfig(sitemapInput, { baseUrl });
  const robots = resolveDocsRobotsConfig(robotsInput, {
    baseUrl:
      typeof robotsInput === "object" ? (robotsInput.baseUrl ?? sitemap.baseUrl) : sitemap.baseUrl,
  });
  const configuredMcp = resolveDocsMcpConfig(mcpInput, { defaultName: resolvedSiteTitle });
  const disabledMcp: DocsMcpResolvedConfig = resolveDocsMcpConfig(false, {
    defaultName: resolvedSiteTitle,
  });
  const mcp = staticExport ? disabledMcp : configuredMcp;
  const feedbackConfig = resolveDocsAgentFeedbackConfig(staticExport ? false : config?.feedback);
  const feedback = {
    enabled: feedbackConfig.enabled,
    route: feedbackConfig.route,
    schemaRoute: feedbackConfig.schemaRoute,
  };
  const apiReferenceInput =
    config?.apiReference ?? readStaticApiReferenceEnabled(configContent) ?? false;
  const openapi = staticExport
    ? { enabled: false as const }
    : resolveApiReferenceOpenApiDiscovery(apiReferenceInput);
  const llms: DocsLlmsDiscoveryConfig = {
    enabled: llmsEnabled,
    baseUrl,
    siteTitle: resolvedSiteTitle,
    siteDescription,
    maxChars: llmsConfig?.maxChars,
    sections: llmsConfig?.sections,
    openapi,
  };
  const documentOptions = {
    origin: baseUrl ?? "/",
    entry: routeEntry || "docs",
    search: staticExport ? false : config?.search,
    mcp,
    feedback,
    llms,
    sitemap: sitemapInput,
    robots: robotsInput,
    openapi,
    markdown: { acceptHeader: false },
  };
  let outputs: PlannedOutput[] = [];
  const internalOutputs: PlannedInternalOutput[] = [];

  for (const { page } of localizedPages) {
    addOutput(
      outputs,
      publicDir,
      staticMarkdownRoute(page, sourceEntry, routeEntry),
      "page",
      "text/markdown",
      renderDocsMarkdownDocument(
        {
          ...page,
          markdownUrl: staticMarkdownRoute(page, sourceEntry, routeEntry),
        },
        {
          llms,
          origin: baseUrl,
          sitemap: sitemapInput,
        },
      ),
    );
  }

  if (llmsEnabled) {
    const llmsContent = renderDocsLlmsTxt(
      pages.map((page) => ({
        url: page.url,
        markdownUrl: staticMarkdownRoute(page, sourceEntry, routeEntry),
        title: page.title,
        description: page.description,
        content:
          page.agentRawContent ?? page.agentFallbackRawContent ?? page.rawContent ?? page.content,
      })),
      llms,
    );
    for (const route of [DEFAULT_LLMS_TXT_ROUTE, DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE]) {
      addOutput(outputs, publicDir, route, "llms", "text/plain", llmsContent.llmsTxt);
    }
    for (const route of [DEFAULT_LLMS_FULL_TXT_ROUTE, DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE]) {
      addOutput(outputs, publicDir, route, "llms", "text/plain", llmsContent.llmsFullTxt);
    }
    const sectionRoutes = new Set(
      llmsContent.sections.flatMap((section) => [section.route, section.fullRoute]),
    );
    const llmsBaseRoutes = new Set([sourceEntry, routeEntry].filter(Boolean));
    for (const llmsBaseRoute of llmsBaseRoutes) {
      const entryLlmsRoute = `/${llmsBaseRoute}/llms.txt`;
      const entryLlmsFullRoute = `/${llmsBaseRoute}/llms-full.txt`;
      if (!sectionRoutes.has(entryLlmsRoute)) {
        addOutput(outputs, publicDir, entryLlmsRoute, "llms", "text/plain", llmsContent.llmsTxt);
      }
      if (!sectionRoutes.has(entryLlmsFullRoute)) {
        addOutput(
          outputs,
          publicDir,
          entryLlmsFullRoute,
          "llms",
          "text/plain",
          llmsContent.llmsFullTxt,
        );
      }
    }
    for (const section of llmsContent.sections) {
      addOutput(outputs, publicDir, section.route, "llms", "text/plain", section.llmsTxt);
      addOutput(outputs, publicDir, section.fullRoute, "llms", "text/plain", section.llmsFullTxt);
    }
  }

  const discovery = buildDocsAgentDiscoverySpec({
    ...documentOptions,
    i18n,
  });
  const discoveryWithBundle = {
    ...discovery,
    staticBundle: {
      format: "farming-labs-agent-bundle.v1",
      manifest: AGENT_BUNDLE_MANIFEST_ROUTE,
      check: "docs agent export --check",
      locales: i18n
        ? {
            default: i18n.defaultLocale,
            pathPattern: `${routeEntry ? `/${routeEntry}` : ""}/{locale}/{slug}.md`,
          }
        : undefined,
    },
  };
  const discoveryJson = JSON.stringify(discoveryWithBundle, null, 2);
  for (const route of [
    DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE,
    DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE,
  ]) {
    addOutput(outputs, publicDir, route, "discovery", "application/json", discoveryJson);
  }

  const generatedSkill = renderDocsSkillDocument(documentOptions);
  const rootSkillPath = path.join(rootDir, "skill.md");
  const publicSkill = existsSync(rootSkillPath)
    ? readFileSync(rootSkillPath, "utf-8")
    : generatedSkill;
  for (const route of [DEFAULT_SKILL_MD_ROUTE, DEFAULT_SKILL_MD_WELL_KNOWN_ROUTE]) {
    addOutput(outputs, publicDir, route, "skill", "text/markdown", publicSkill);
  }
  addOutput(outputs, publicDir, SKILL_CANONICAL_ROUTE, "skill", "text/markdown", generatedSkill);

  const generatedAgents = `${AGENT_EXPORT_AGENTS_MARKER}\n${renderDocsAgentsDocument(
    documentOptions,
  )}`;
  const publicAgentsSource = findPublicAgentsSource(publicDir) ?? generatedAgents;
  for (const route of [
    DEFAULT_AGENTS_MD_ROUTE,
    DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
    DEFAULT_AGENT_MD_ROUTE,
    DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  ]) {
    addOutput(outputs, publicDir, route, "agents", "text/markdown", publicAgentsSource);
  }
  outputs = resolveUserOwnedAgentsOutputs(outputs);

  if (sitemap.enabled) {
    const sitemapManifest = deterministicSitemapManifest({
      rootDir,
      pages: pages.map((page) => ({
        ...page,
        markdownUrl: staticMarkdownRoute(page, sourceEntry, routeEntry),
      })),
      entry: routeEntry || "docs",
      siteTitle: resolvedSiteTitle,
      baseUrl: sitemap.baseUrl,
    });
    const sitemapManifestPath = resolveContainedPath(rootDir, sitemap.manifestPath);
    if (!sitemapManifestPath) {
      throw new Error("sitemap.manifestPath must stay inside the project root for agent export.");
    }
    if (sitemapManifestPath === path.join(rootDir, AGENT_BUNDLE_INTERNAL_MANIFEST)) {
      throw new Error(
        `sitemap.manifestPath conflicts with ${AGENT_BUNDLE_INTERNAL_MANIFEST}. Choose a different sitemap manifest path.`,
      );
    }
    internalOutputs.push({
      absolutePath: sitemapManifestPath,
      path: path.relative(rootDir, sitemapManifestPath).replace(/\\/g, "/"),
      kind: "sitemap",
      content: `${JSON.stringify(sitemapManifest, null, 2)}\n`,
    });
    if (sitemap.xml.enabled) {
      addOutput(
        outputs,
        publicDir,
        sitemap.xml.route,
        "sitemap",
        "application/xml",
        renderDocsSitemapXml(sitemapManifest, {
          baseUrl: sitemap.baseUrl,
          includeLastmod: sitemap.xml.includeLastmod,
        }),
      );
    }
    if (sitemap.markdown.enabled) {
      const sitemapMarkdown = renderDocsSitemapMarkdown(sitemapManifest, {
        baseUrl: sitemap.baseUrl,
        includeDescriptions: sitemap.markdown.includeDescriptions,
        includeLastmod: sitemap.markdown.includeLastmod,
        linkTarget: sitemap.markdown.linkTarget,
      });
      for (const route of [
        sitemap.markdown.route,
        sitemap.markdown.docsRoute,
        sitemap.markdown.wellKnownRoute,
      ]) {
        if (route) {
          addOutput(outputs, publicDir, route, "sitemap", "text/markdown", sitemapMarkdown);
        }
      }
    }
  }

  if (robots.enabled) {
    outputs.push(resolveRobotsOutput(publicDir, routeEntry || "docs", sitemapInput, robots));
  }

  outputs = resolveUserOwnedOverrides(outputs, previous);
  outputs.sort((left, right) => left.publicPath.localeCompare(right.publicPath));
  const manifest = buildAgentBundleManifest({
    sourceEntry,
    entry: routeEntry,
    publicDirectory,
    baseUrl,
    outputs,
    internalOutputs,
    pages: localizedPages,
  });
  const manifestJson = `${JSON.stringify(manifest, null, 2)}\n`;
  const publicManifestPath = publicFilePath(publicDir, AGENT_BUNDLE_MANIFEST_ROUTE);
  const internalManifestPath = path.join(rootDir, AGENT_BUNDLE_INTERNAL_MANIFEST);
  const changed = changedOutputs(outputs);
  const changedInternalOutputs = internalOutputs.filter(
    (output) => readExisting(output.absolutePath) !== output.content,
  );
  if (readExisting(publicManifestPath) !== manifestJson) {
    changed.push({
      absolutePath: publicManifestPath,
      publicPath: publicRelativePath(publicDir, publicManifestPath),
      route: AGENT_BUNDLE_MANIFEST_ROUTE,
      kind: "discovery",
      mediaType: "application/json",
      content: manifestJson,
      managed: true,
    });
  }
  const internalChanged = readExisting(internalManifestPath) !== manifestJson;
  const stalePaths = staleManagedPaths(publicDir, previous, outputs);
  const staleInternal = staleInternalPaths(rootDir, previous, internalOutputs);

  if (
    options.check &&
    (changed.length > 0 ||
      changedInternalOutputs.length > 0 ||
      internalChanged ||
      stalePaths.length > 0 ||
      staleInternal.length > 0)
  ) {
    throw new Error(
      `Static Agent Bundle is stale (${changed.length + changedInternalOutputs.length + (internalChanged ? 1 : 0) + stalePaths.length + staleInternal.length} output(s)). Run \`docs agent export --public\` to update it.`,
    );
  }

  if (!options.check) {
    for (const output of outputs) {
      if (readExisting(output.absolutePath) !== output.content) {
        atomicWriteFile(output.absolutePath, output.content);
      }
    }
    for (const output of internalOutputs) {
      if (readExisting(output.absolutePath) !== output.content) {
        atomicWriteFile(output.absolutePath, output.content);
      }
    }
    atomicWriteFile(publicManifestPath, manifestJson);
    atomicWriteFile(internalManifestPath, manifestJson);
    const removed = removeStaleManagedFiles(publicDir, previous, stalePaths);
    removed.push(...removeStaleInternalFiles(rootDir, previous, staleInternal));
    for (const filePath of removed) {
      console.log(pc.dim(`Removed ${path.relative(rootDir, filePath).replace(/\\/g, "/")}`));
    }
  }

  const managedCount = manifest.files.filter((file) => file.managed).length;
  const customCount = manifest.files.length - managedCount;
  console.log(
    pc.green(
      options.check
        ? `Static Agent Bundle is current (${manifest.files.length} files, ${manifest.pages.length} pages).`
        : `Exported Static Agent Bundle (${manifest.files.length} files, ${manifest.pages.length} pages).`,
    ),
  );
  console.log(pc.dim(`${publicDirectory}/.well-known/agent-bundle.json`));
  console.log(pc.dim(AGENT_BUNDLE_INTERNAL_MANIFEST));
  if (customCount > 0) {
    console.log(pc.yellow(`Preserved ${customCount} user-owned public file(s).`));
  }
}

export function printAgentExportHelp(): void {
  console.log(`
${pc.bold("docs agent export")} — Export a complete static Agent Bundle.

${pc.dim("Usage:")}
  pnpm exec docs ${pc.cyan("agent export --public")}
  pnpm exec docs ${pc.cyan("agent export --check")}

${pc.dim("Options:")}
  ${pc.cyan("--public")}            Write static agent files to ${pc.dim("public/")} or SvelteKit ${pc.dim("static/")}
  ${pc.cyan("--check")}             Fail when exported files or their SHA-256 manifest are stale
  ${pc.cyan("--config <path>")}     Use a custom docs config path instead of ${pc.dim("docs.config.ts[x]")}
  ${pc.cyan("-h, --help")}          Show this help message
`);
}
