import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateAgents, parseAgentsGenerateArgs } from "./agents.js";

describe("agents cli", () => {
  const originalCwd = process.cwd();
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(path.join(os.tmpdir(), "docs-agents-"));
    vi.spyOn(console, "log").mockImplementation(() => undefined);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    vi.restoreAllMocks();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function writeConfig() {
    writeFileSync(
      path.join(tmpDir, "docs.config.ts"),
      `export default {
  entry: "docs",
  nav: { title: "Agent Docs" },
  metadata: { description: "Docs for agents." },
  llmsTxt: { enabled: true, baseUrl: "https://docs.example.com" },
  sitemap: { enabled: true, baseUrl: "https://docs.example.com" },
  robots: { enabled: true },
  mcp: true,
};
`,
      "utf-8",
    );
  }

  it("parses generate flags", () => {
    expect(
      parseAgentsGenerateArgs(["--config", "src/lib/docs.config.ts", "--path", "docs/AGENTS.md"]),
    ).toEqual({
      configPath: "src/lib/docs.config.ts",
      path: "docs/AGENTS.md",
    });

    expect(parseAgentsGenerateArgs(["AGENTS.md", "--force", "--check"])).toEqual({
      path: "AGENTS.md",
      force: true,
      check: true,
    });
  });

  it("writes root and public AGENTS.md aliases by default", async () => {
    writeConfig();
    process.chdir(tmpDir);

    await generateAgents();

    const rootAgents = path.join(tmpDir, "AGENTS.md");
    const publicAgents = path.join(tmpDir, "public", "AGENTS.md");
    const publicWellKnown = path.join(tmpDir, "public", ".well-known", "AGENTS.md");
    const publicAlias = path.join(tmpDir, "public", "AGENT.md");

    expect(existsSync(rootAgents)).toBe(true);
    expect(existsSync(publicAgents)).toBe(true);
    expect(existsSync(publicWellKnown)).toBe(true);
    expect(existsSync(publicAlias)).toBe(true);

    const content = readFileSync(rootAgents, "utf-8");
    expect(content).toContain("Generated by @farming-labs/docs agents generate");
    expect(content).toContain("# Agent Instructions");
    expect(content).toContain("Site: Agent Docs");
    expect(content).toContain("Base URL: https://docs.example.com");
    expect(content).toContain("/AGENTS.md");
    expect(content).toContain("/api/docs?format=agents");
    expect(readFileSync(publicAgents, "utf-8")).toBe(content);
  });

  it("keeps a custom root AGENTS.md and copies it to missing public aliases", async () => {
    writeConfig();
    writeFileSync(path.join(tmpDir, "AGENTS.md"), "# Custom agents\n\nUse this first.\n", "utf-8");
    process.chdir(tmpDir);

    await generateAgents();

    expect(readFileSync(path.join(tmpDir, "AGENTS.md"), "utf-8")).toBe(
      "# Custom agents\n\nUse this first.\n",
    );
    expect(readFileSync(path.join(tmpDir, "public", "AGENTS.md"), "utf-8")).toBe(
      "# Custom agents\n\nUse this first.\n",
    );
  });

  it("fails check mode when generated files are stale", async () => {
    writeConfig();
    process.chdir(tmpDir);

    await expect(generateAgents({ check: true })).rejects.toThrow("AGENTS.md output is stale");
  });
});
