import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import pc from "picocolors";
import {
  DEFAULT_AGENT_MD_ROUTE,
  DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  DEFAULT_AGENTS_MD_ROUTE,
  DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
  DEFAULT_OPENAPI_SCHEMA_ROUTE,
  renderDocsAgentsDocument,
  resolveDocsAgentFeedbackConfig,
} from "../agent.js";
import type { DocsConfig } from "../types.js";
import { resolveApiReferenceConfig, resolveDocsMcpConfig } from "../server.js";
import {
  extractNestedObjectLiteral,
  loadDocsConfigModule,
  readBooleanProperty,
  readNavTitle,
  readStringProperty,
  readTopLevelStringProperty,
  resolveDocsConfigPath,
} from "./config.js";
import { detectFramework } from "./utils.js";

export interface AgentsGenerateOptions {
  configPath?: string;
  path?: string;
  force?: boolean;
  check?: boolean;
}

export interface ParsedAgentsGenerateArgs extends AgentsGenerateOptions {
  help?: boolean;
}

const AGENTS_GENERATED_MARKER = "<!-- Generated by @farming-labs/docs agents generate. -->";

function parseInlineFlag(arg: string): { key: string; value?: string } {
  const [rawKey, value] = arg.slice(2).split("=", 2);
  return { key: rawKey.trim(), value };
}

export function parseAgentsGenerateArgs(argv: string[]): ParsedAgentsGenerateArgs {
  const parsed: ParsedAgentsGenerateArgs = {};

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--help" || arg === "-h") {
      parsed.help = true;
      continue;
    }

    if (arg === "--force") {
      parsed.force = true;
      continue;
    }

    if (arg === "--check") {
      parsed.check = true;
      continue;
    }

    if (arg.startsWith("--config=")) {
      const value = parseInlineFlag(arg).value;
      if (!value) throw new Error("Missing value for --config.");
      parsed.configPath = value;
      continue;
    }

    if (arg === "--config") {
      const value = argv[index + 1];
      if (!value || value.startsWith("--")) throw new Error("Missing value for --config.");
      parsed.configPath = value;
      index += 1;
      continue;
    }

    if (arg.startsWith("--path=")) {
      const value = parseInlineFlag(arg).value;
      if (!value) throw new Error("Missing value for --path.");
      parsed.path = value;
      continue;
    }

    if (arg === "--path") {
      const value = argv[index + 1];
      if (!value || value.startsWith("--")) throw new Error("Missing value for --path.");
      parsed.path = value;
      index += 1;
      continue;
    }

    if (!arg.startsWith("--") && !parsed.path) {
      parsed.path = arg;
      continue;
    }

    throw new Error(`Unknown agents generate flag: ${arg}.`);
  }

  return parsed;
}

function readTopLevelBooleanProperty(content: string, key: string): boolean | undefined {
  const match = content.match(new RegExp(`\\b${key}\\b\\s*:\\s*(true|false)`));
  return match ? match[1] === "true" : undefined;
}

function readLlmsBaseUrlFromConfig(content: string, config?: DocsConfig): string | undefined {
  if (config?.llmsTxt && typeof config.llmsTxt === "object") return config.llmsTxt.baseUrl;
  const block = extractNestedObjectLiteral(content, ["llmsTxt"]);
  return block ? readStringProperty(block, "baseUrl") : undefined;
}

function readSitemapBaseUrlFromConfig(content: string, config?: DocsConfig): string | undefined {
  if (config?.sitemap && typeof config.sitemap === "object") return config.sitemap.baseUrl;
  const block = extractNestedObjectLiteral(content, ["sitemap"]);
  return block ? readStringProperty(block, "baseUrl") : undefined;
}

function readCloudApiRouteFromConfig(content: string, config?: DocsConfig): string | undefined {
  if (typeof config?.cloud?.apiRoute === "string") return config.cloud.apiRoute;
  const block = extractNestedObjectLiteral(content, ["cloud"]);
  return block ? readStringProperty(block, "apiRoute") : undefined;
}

function readRobotsConfigFromStatic(content: string): boolean | { enabled?: boolean } | undefined {
  const topLevelBoolean = readTopLevelBooleanProperty(content, "robots");
  if (typeof topLevelBoolean === "boolean") return topLevelBoolean;

  const block = extractNestedObjectLiteral(content, ["robots"]);
  if (!block) return undefined;

  return {
    enabled: readBooleanProperty(block, "enabled") ?? true,
  };
}

function resolvePublicDir(rootDir: string): string {
  const framework = detectFramework(rootDir);
  if (framework === "sveltekit") return path.join(rootDir, "static");
  return path.join(rootDir, "public");
}

function resolveAgentsPath(rootDir: string, options: AgentsGenerateOptions): string {
  if (options.path) {
    return path.isAbsolute(options.path) ? options.path : path.resolve(rootDir, options.path);
  }

  return path.join(rootDir, "AGENTS.md");
}

function publicFilePath(rootDir: string, route: string): string {
  return path.join(resolvePublicDir(rootDir), route.replace(/^\/+/, ""));
}

function normalizeGeneratedContent(content: string): string {
  return `${AGENTS_GENERATED_MARKER}\n${content.trimEnd()}\n`;
}

function normalizeCustomContent(content: string): string {
  return content.endsWith("\n") ? content : `${content}\n`;
}

function isManagedAgentsFile(content: string): boolean {
  return content.includes(AGENTS_GENERATED_MARKER);
}

function writeIfNeeded(
  filePath: string,
  content: string,
  options: { force?: boolean; check?: boolean },
): "changed" | "current" | "kept" {
  const current = existsSync(filePath) ? readFileSync(filePath, "utf-8") : undefined;
  if (current === content) return "current";

  if (current !== undefined && !options.force && !isManagedAgentsFile(current)) {
    return "kept";
  }

  if (options.check) return "changed";

  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf-8");
  return "changed";
}

function resolveOpenApiDiscovery(config?: DocsConfig) {
  const apiReference = resolveApiReferenceConfig(config?.apiReference);
  if (!apiReference.enabled) return { enabled: false };

  return {
    enabled: true,
    url: DEFAULT_OPENAPI_SCHEMA_ROUTE,
    urlSource: "default" as const,
    source: apiReference.specUrl ? ("configured" as const) : ("generated" as const),
    specUrl: apiReference.specUrl,
    apiReferencePath: `/${apiReference.path}`,
  };
}

export async function generateAgents(options: AgentsGenerateOptions = {}): Promise<void> {
  const rootDir = process.cwd();
  const loadedConfigModule = await loadDocsConfigModule(rootDir, options.configPath);
  const configPath = loadedConfigModule?.path ?? resolveDocsConfigPath(rootDir, options.configPath);
  const configContent = readFileSync(configPath, "utf-8");
  const config = loadedConfigModule?.config;

  const entry = config?.entry ?? readTopLevelStringProperty(configContent, "entry") ?? "docs";
  const siteTitle =
    typeof config?.nav?.title === "string"
      ? config.nav.title
      : (readNavTitle(configContent) ?? "Documentation");
  const siteDescription =
    typeof config?.metadata?.description === "string" ? config.metadata.description : undefined;
  const baseUrl =
    readLlmsBaseUrlFromConfig(configContent, config) ??
    readSitemapBaseUrlFromConfig(configContent, config);
  const apiRoute = readCloudApiRouteFromConfig(configContent, config);
  const llmsTxt = config?.llmsTxt;
  const llmsEnabled =
    llmsTxt === false ? false : typeof llmsTxt === "object" ? (llmsTxt.enabled ?? true) : true;
  const llmsConfig = typeof llmsTxt === "object" ? llmsTxt : undefined;
  const robotsInput = config?.robots ?? readRobotsConfigFromStatic(configContent) ?? true;
  const rootAgentsPath = resolveAgentsPath(rootDir, options);
  const generatedContent = normalizeGeneratedContent(
    renderDocsAgentsDocument({
      origin: baseUrl ?? "http://localhost",
      entry,
      apiRoute,
      search: config?.search,
      mcp: resolveDocsMcpConfig(config?.mcp),
      feedback: resolveDocsAgentFeedbackConfig(config?.feedback),
      llms: {
        enabled: llmsEnabled,
        baseUrl,
        siteTitle,
        siteDescription,
        maxChars: llmsConfig?.maxChars,
        sections: llmsConfig?.sections,
      },
      sitemap: config?.sitemap,
      robots: robotsInput,
      openapi: resolveOpenApiDiscovery(config),
      markdown: {
        acceptHeader: false,
      },
    }),
  );
  const existingRoot = existsSync(rootAgentsPath) ? readFileSync(rootAgentsPath, "utf-8") : null;
  const rootIsCustom =
    existingRoot !== null && !options.force && !isManagedAgentsFile(existingRoot);
  const sourceContent = rootIsCustom ? normalizeCustomContent(existingRoot) : generatedContent;
  const writes: string[] = [];
  const kept: string[] = [];

  const rootStatus = writeIfNeeded(rootAgentsPath, sourceContent, options);
  if (rootStatus === "changed") writes.push(rootAgentsPath);
  if (rootStatus === "kept") kept.push(rootAgentsPath);

  for (const route of [
    DEFAULT_AGENTS_MD_ROUTE,
    DEFAULT_AGENTS_MD_WELL_KNOWN_ROUTE,
    DEFAULT_AGENT_MD_ROUTE,
    DEFAULT_AGENT_MD_WELL_KNOWN_ROUTE,
  ]) {
    const filePath = publicFilePath(rootDir, route);
    const status = writeIfNeeded(filePath, sourceContent, options);
    if (status === "changed") writes.push(filePath);
    if (status === "kept") kept.push(filePath);
  }

  if (options.check && writes.length > 0) {
    throw new Error("AGENTS.md output is stale. Run `docs agents generate` to update it.");
  }

  const relativeRoot = path.relative(rootDir, rootAgentsPath).replace(/\\/g, "/");
  console.log(
    writes.length > 0
      ? pc.green(`Generated agent instructions at ${relativeRoot}.`)
      : pc.green(`Agent instructions are current at ${relativeRoot}.`),
  );

  for (const filePath of writes) {
    if (filePath === rootAgentsPath) continue;
    console.log(pc.dim(path.relative(rootDir, filePath).replace(/\\/g, "/")));
  }

  for (const filePath of kept) {
    console.log(
      pc.yellow(`Kept user-owned ${path.relative(rootDir, filePath).replace(/\\/g, "/")}.`),
    );
  }
}

export function printAgentsGenerateHelp() {
  console.log(`
${pc.bold("docs agents generate")} — Generate AGENTS.md instructions for coding agents.

${pc.dim("Usage:")}
  pnpm exec docs ${pc.cyan("agents generate")} ${pc.dim("[path]")}

${pc.dim("Options:")}
  ${pc.cyan("--path <path>")}       Write the root instructions file; defaults to ${pc.dim("AGENTS.md")}
  ${pc.cyan("--force")}             Replace existing AGENTS.md/static files
  ${pc.cyan("--check")}             Fail if generated output would change
  ${pc.cyan("--config <path>")}     Use a custom docs config path instead of ${pc.dim("docs.config.ts[x]")}
  ${pc.cyan("-h, --help")}          Show this help message
`);
}
