import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import path from "node:path";
import pc from "picocolors";
import {
  buildNormalizedOpenApiModel,
  type NormalizedOpenApiMediaType,
  type NormalizedOpenApiOperation,
  type NormalizedOpenApiParameter,
  type NormalizedOpenApiResponse,
} from "../openapi-operations.js";
import { displayOpenApiCliSource, loadOpenApiCliSource } from "./openapi-source.js";

export interface OpenApiSdkOptions {
  source?: string;
  output?: string;
  clientName?: string;
  baseUrl?: string;
  sourceBaseUrl?: string;
  check: boolean;
  dryRun: boolean;
  force: boolean;
  help: boolean;
  rootDir?: string;
}

export interface OpenApiSdkReport {
  format: "farming-labs-openapi-sdk.v1";
  source: string;
  output: string;
  clientName: string;
  operationCount: number;
  schemaCount: number;
  changed: boolean;
  wrote: boolean;
}

interface TypeScriptSchemaContext {
  document: Record<string, unknown>;
  referenceNames: Map<string, string>;
  references: Set<string>;
}

interface GeneratedOperationNames {
  methodName: string;
  inputName: string;
  responseName: string;
}

interface ComponentSchema {
  name: string;
  reference: string;
  schema: unknown;
}

const GENERATED_SDK_MARKER = "// Generated by @farming-labs/docs openapi sdk. Do not edit.";
const GENERATED_TYPE_NAMES = new Set(["ApiClientOptions", "ApiError", "ApiResponse"]);
const RESERVED_METHOD_NAMES = new Set(["constructor"]);

export function parseOpenApiSdkArgs(argv: string[]): OpenApiSdkOptions {
  const positionals: string[] = [];
  let source: string | undefined;
  let output: string | undefined;
  let clientName: string | undefined;
  let baseUrl: string | undefined;
  let sourceBaseUrl: string | undefined;
  let check = false;
  let dryRun = false;
  let force = false;
  let help = false;

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index] ?? "";
    if (argument === "--help" || argument === "-h") {
      help = true;
      continue;
    }
    if (argument === "--check") {
      check = true;
      continue;
    }
    if (argument === "--dry-run") {
      dryRun = true;
      continue;
    }
    if (argument === "--force") {
      force = true;
      continue;
    }
    if (!argument.startsWith("--")) {
      positionals.push(argument);
      continue;
    }

    const separator = argument.indexOf("=");
    const flag = argument.slice(2, separator === -1 ? undefined : separator);
    const inlineValue = separator === -1 ? undefined : argument.slice(separator + 1);
    const value = inlineValue ?? argv[index + 1];
    if (value === undefined || value.startsWith("--")) {
      throw new Error(`Missing value for --${flag}.`);
    }
    if (inlineValue === undefined) index += 1;

    if (flag === "source") source = value;
    else if (flag === "output" || flag === "out") output = value;
    else if (flag === "client-name" || flag === "name") clientName = value;
    else if (flag === "base-url") baseUrl = value;
    else if (flag === "source-base-url") sourceBaseUrl = value;
    else throw new Error(`Unknown OpenAPI SDK option: --${flag}.`);
  }

  for (const positional of positionals) {
    if (!source) source = positional;
    else throw new Error("Pass exactly one OpenAPI source.");
  }
  if (check && dryRun) throw new Error("Use either --check or --dry-run, not both.");
  if (!help && !source) throw new Error("Pass an OpenAPI source.");
  if (!help && !output) throw new Error("Pass --output <path> for the generated TypeScript SDK.");

  return {
    source,
    output,
    clientName,
    baseUrl,
    sourceBaseUrl,
    check,
    dryRun,
    force,
    help,
  };
}

export async function runOpenApiSdk(options: OpenApiSdkOptions): Promise<OpenApiSdkReport> {
  if (!options.source || !options.output) {
    throw new Error("OpenAPI SDK source and output are required.");
  }
  const rootDir = path.resolve(options.rootDir ?? process.cwd());
  const outputPath = resolveOutputPath(rootDir, options.output);
  const document = await loadOpenApiCliSource(options.source, {
    rootDir,
    baseUrl: options.sourceBaseUrl,
  });
  const model = buildNormalizedOpenApiModel(document);
  const clientName = normalizeTypeName(options.clientName ?? `${model.title} Client`);
  const code = generateOpenApiTypeScriptSdk(document, {
    clientName,
    baseUrl: options.baseUrl,
    source: displayOpenApiCliSource(options.source),
  });
  const current = existsSync(outputPath) ? readFileSync(outputPath, "utf-8") : undefined;
  const changed = current !== code;
  const report: OpenApiSdkReport = {
    format: "farming-labs-openapi-sdk.v1",
    source: displayOpenApiCliSource(options.source),
    output: normalizeRelativePath(path.relative(rootDir, outputPath)),
    clientName,
    operationCount: model.operationCount,
    schemaCount: collectComponentSchemas(document).length,
    changed,
    wrote: false,
  };

  if (options.dryRun) {
    console.log(code);
    return report;
  }
  if (options.check) {
    if (changed) {
      console.error(
        pc.red(
          `${report.output} is missing or stale. Run docs openapi sdk ${options.source} --output ${options.output}.`,
        ),
      );
      process.exitCode = 1;
    } else {
      console.log(pc.green(`${report.output} is up to date.`));
    }
    return report;
  }
  if (current !== undefined && !current.startsWith(GENERATED_SDK_MARKER) && !options.force) {
    throw new Error(
      `Refusing to replace non-generated file ${report.output}. Pass --force only after reviewing that file.`,
    );
  }

  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, code, "utf-8");
  report.wrote = true;
  console.log(
    pc.green(
      `${changed ? "Generated" : "Refreshed"} ${report.output} with ${report.operationCount} operation${report.operationCount === 1 ? "" : "s"} and ${report.schemaCount} schema${report.schemaCount === 1 ? "" : "s"}.`,
    ),
  );
  return report;
}

export function generateOpenApiTypeScriptSdk(
  document: Record<string, unknown>,
  options: { clientName?: string; baseUrl?: string; source?: string } = {},
): string {
  const model = buildNormalizedOpenApiModel(document);
  const usedTypeNames = new Set(GENERATED_TYPE_NAMES);
  const clientName = claimName(
    normalizeTypeName(options.clientName ?? `${model.title} Client`),
    usedTypeNames,
  );
  const components = collectComponentSchemas(document, usedTypeNames);
  const referenceNames = new Map(
    components.map((component) => [component.reference, component.name]),
  );
  const operationNames = new Map<NormalizedOpenApiOperation, GeneratedOperationNames>();
  const usedMethodNames = new Set<string>();
  for (const operation of model.operations) {
    const baseName = normalizeTypeName(operation.operationId);
    operationNames.set(operation, {
      methodName: claimName(normalizeMethodName(operation.operationId), usedMethodNames),
      inputName: claimName(`${baseName}Input`, usedTypeNames),
      responseName: claimName(`${baseName}Response`, usedTypeNames),
    });
  }

  const schemaContext: TypeScriptSchemaContext = {
    document,
    referenceNames,
    references: new Set(),
  };
  const defaultBaseUrl = resolveSdkBaseUrl(options.baseUrl, model.servers);
  const lines: string[] = [
    GENERATED_SDK_MARKER,
    `// Source: ${sanitizeLineComment(options.source ?? "OpenAPI contract")}`,
    "",
    "export interface ApiClientOptions {",
    "  baseUrl?: string;",
    "  fetch?: typeof fetch;",
    "  headers?: HeadersInit;",
    "}",
    "",
    "export interface ApiResponse<TStatus extends number | string, TData> {",
    "  status: TStatus;",
    "  data: TData;",
    "  headers: Headers;",
    "}",
    "",
    "export class ApiError<TData = unknown> extends Error {",
    "  readonly status: number;",
    "  readonly data: TData;",
    "  readonly headers: Headers;",
    "",
    "  constructor(status: number, data: TData, headers: Headers) {",
    "    super(`API request failed with status ${status}.`);",
    '    this.name = "ApiError";',
    "    this.status = status;",
    "    this.data = data;",
    "    this.headers = headers;",
    "  }",
    "}",
  ];

  for (const component of components) {
    lines.push(
      "",
      `export type ${component.name} = ${schemaToTypeScript(component.schema, schemaContext)};`,
    );
  }

  for (const operation of model.operations) {
    const names = operationNames.get(operation)!;
    lines.push("", ...renderOperationTypes(operation, names, schemaContext));
  }

  lines.push(
    "",
    `const DEFAULT_BASE_URL = ${JSON.stringify(defaultBaseUrl)};`,
    "",
    "function joinUrl(baseUrl: string, pathname: string): string {",
    '  return `${baseUrl.replace(/\\/+$/, "")}/${pathname.replace(/^\\/+/, "")}`;',
    "}",
    "",
    "function appendQueryParameter(searchParams: URLSearchParams, name: string, value: unknown): void {",
    "  if (value === undefined || value === null) return;",
    "  if (Array.isArray(value)) {",
    "    for (const entry of value) appendQueryParameter(searchParams, name, entry);",
    "    return;",
    "  }",
    '  searchParams.append(name, typeof value === "object" ? JSON.stringify(value) : String(value));',
    "}",
    "",
    "async function parseApiResponse(response: Response): Promise<unknown> {",
    "  if (response.status === 204 || response.status === 205) return undefined;",
    '  const contentLength = response.headers.get("content-length");',
    '  if (contentLength === "0") return undefined;',
    '  const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";',
    '  if (contentType.includes("json") || contentType.includes("+json")) return response.json();',
    "  return response.text();",
    "}",
    "",
    `export class ${clientName} {`,
    "  private readonly baseUrl: string;",
    "  private readonly fetchImpl: typeof fetch;",
    "  private readonly defaultHeaders: Headers;",
    "",
    "  constructor(options: ApiClientOptions = {}) {",
    "    this.baseUrl = options.baseUrl ?? DEFAULT_BASE_URL;",
    "    if (!this.baseUrl) {",
    '      throw new Error("A baseUrl is required because the OpenAPI contract has no absolute server URL.");',
    "    }",
    "    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);",
    "    this.defaultHeaders = new Headers(options.headers);",
    "  }",
  );
  for (const operation of model.operations) {
    lines.push("", ...renderOperationMethod(operation, operationNames.get(operation)!));
  }
  lines.push("}", "");
  return lines.join("\n");
}

export function printOpenApiSdkHelp(): void {
  console.log(`${pc.bold("docs openapi sdk")} — Generate a typed TypeScript fetch client.

Usage:
  docs openapi sdk <source> --output <path> [options]
  docs api sdk --source <source> --out <path> [options]

Sources:
  Project-relative or absolute JSON/YAML files, file: URLs, and HTTP(S) URLs.

Options:
  ${pc.cyan("--source <source>")}          OpenAPI contract; positional form is also accepted
  ${pc.cyan("--output, --out <path>")}    TypeScript output path inside the project root
  ${pc.cyan("--client-name <name>")}      Generated client class name
  ${pc.cyan("--base-url <url>")}          Override the generated client default base URL
  ${pc.cyan("--source-base-url <url>")}   Resolve a request-relative remote source
  ${pc.cyan("--check")}                   Fail when the generated file is missing or stale
  ${pc.cyan("--dry-run")}                 Print generated TypeScript without writing
  ${pc.cyan("--force")}                   Replace an existing non-generated output file
  ${pc.cyan("--help")}                    Show this help
`);
}

function renderOperationTypes(
  operation: NormalizedOpenApiOperation,
  names: GeneratedOperationNames,
  context: TypeScriptSchemaContext,
): string[] {
  const lines = [`export interface ${names.inputName} {`];
  for (const location of ["path", "query", "header", "cookie"] as const) {
    const parameters = operation.parameters.filter((parameter) => parameter.in === location);
    if (parameters.length === 0) continue;
    const required = parameters.some((parameter) => parameter.required);
    lines.push(
      `  ${location}${required ? "" : "?"}: ${renderParameterObject(parameters, context)};`,
    );
  }
  if (operation.requestBody) {
    const media = selectMediaType(operation.requestBody.content);
    lines.push(
      `  body${operation.requestBody.required ? "" : "?"}: ${schemaToTypeScript(media?.schema, context)};`,
    );
  }
  lines.push(
    '  request?: Omit<RequestInit, "method" | "body" | "headers"> & { headers?: HeadersInit };',
    "}",
    "",
    `export type ${names.responseName} = ${renderResponseType(operation.responses, context)};`,
  );
  return lines;
}

function renderOperationMethod(
  operation: NormalizedOpenApiOperation,
  names: GeneratedOperationNames,
): string[] {
  const inputRequired =
    operation.parameters.some((parameter) => parameter.required) ||
    operation.requestBody?.required === true;
  const lines = [
    `  async ${names.methodName}(input: ${names.inputName}${inputRequired ? "" : " = {}"}): Promise<${names.responseName}> {`,
    `    let operationPath = ${JSON.stringify(operation.path)};`,
  ];
  for (const parameter of operation.parameters.filter((entry) => entry.in === "path")) {
    lines.push(
      `    operationPath = operationPath.replaceAll(${JSON.stringify(`{${parameter.name}}`)}, encodeURIComponent(String(input.path[${JSON.stringify(parameter.name)}])));`,
    );
  }
  lines.push("    const url = new URL(joinUrl(this.baseUrl, operationPath));");
  for (const parameter of operation.parameters.filter((entry) => entry.in === "query")) {
    lines.push(
      `    appendQueryParameter(url.searchParams, ${JSON.stringify(parameter.name)}, input.query?.[${JSON.stringify(parameter.name)}]);`,
    );
  }
  lines.push("    const headers = new Headers(this.defaultHeaders);");
  for (const parameter of operation.parameters.filter((entry) => entry.in === "header")) {
    lines.push(
      `    if (input.header?.[${JSON.stringify(parameter.name)}] !== undefined) headers.set(${JSON.stringify(parameter.name)}, String(input.header[${JSON.stringify(parameter.name)}]));`,
    );
  }
  const cookieParameters = operation.parameters.filter((entry) => entry.in === "cookie");
  if (cookieParameters.length > 0) {
    lines.push("    const cookieParts: string[] = [];");
    for (const parameter of cookieParameters) {
      lines.push(
        `    if (input.cookie?.[${JSON.stringify(parameter.name)}] !== undefined) cookieParts.push(${JSON.stringify(`${parameter.name}=`)} + encodeURIComponent(String(input.cookie[${JSON.stringify(parameter.name)}])));`,
      );
    }
    lines.push('    if (cookieParts.length > 0) headers.set("cookie", cookieParts.join("; "));');
  }
  lines.push(
    "    const requestHeaders = new Headers(input.request?.headers);",
    "    requestHeaders.forEach((value, name) => headers.set(name, value));",
    "    const requestOptions = { ...input.request };",
    "    delete requestOptions.headers;",
  );
  const requestMedia = operation.requestBody
    ? selectMediaType(operation.requestBody.content)
    : undefined;
  if (operation.requestBody) {
    if (requestMedia?.mediaType.includes("json") || requestMedia?.mediaType.includes("+json")) {
      lines.push(
        `    headers.set("content-type", ${JSON.stringify(requestMedia.mediaType)});`,
        "    const body = input.body === undefined ? undefined : JSON.stringify(input.body);",
      );
    } else {
      if (requestMedia) {
        lines.push(`    headers.set("content-type", ${JSON.stringify(requestMedia.mediaType)});`);
      }
      lines.push("    const body = input.body as BodyInit | null | undefined;");
    }
  } else {
    lines.push("    const body = undefined;");
  }
  lines.push(
    "    const response = await this.fetchImpl(url, {",
    "      ...requestOptions,",
    `      method: ${JSON.stringify(operation.method)},`,
    "      headers,",
    "      body,",
    "    });",
    "    const data = await parseApiResponse(response);",
    "    if (!response.ok) throw new ApiError(response.status, data, response.headers);",
    `    return { status: response.status, data, headers: response.headers } as ${names.responseName};`,
    "  }",
  );
  return lines;
}

function renderParameterObject(
  parameters: NormalizedOpenApiParameter[],
  context: TypeScriptSchemaContext,
): string {
  return `{ ${parameters
    .map(
      (parameter) =>
        `${JSON.stringify(parameter.name)}${parameter.required ? "" : "?"}: ${schemaToTypeScript(parameter.schema, context)}`,
    )
    .join("; ")} }`;
}

function renderResponseType(
  responses: NormalizedOpenApiResponse[],
  context: TypeScriptSchemaContext,
): string {
  const successful = responses.filter(
    (response) => /^2\d\d$/.test(response.status) || /^2XX$/i.test(response.status),
  );
  const candidates =
    successful.length > 0
      ? successful
      : responses.filter((response) => response.status === "default");
  if (candidates.length === 0) return "ApiResponse<number, unknown>";
  return candidates
    .map((response) => {
      const media = selectMediaType(response.content);
      const data = media ? schemaToTypeScript(media.schema, context) : "undefined";
      const status = /^\d+$/.test(response.status) ? response.status : "number";
      return `ApiResponse<${status}, ${data}>`;
    })
    .join(" | ");
}

function selectMediaType(
  mediaTypes: NormalizedOpenApiMediaType[],
): NormalizedOpenApiMediaType | undefined {
  return (
    mediaTypes.find((entry) => entry.mediaType === "application/json") ??
    mediaTypes.find((entry) => entry.mediaType.includes("+json")) ??
    mediaTypes[0]
  );
}

function collectComponentSchemas(
  document: Record<string, unknown>,
  usedNames = new Set<string>(),
): ComponentSchema[] {
  const components = asRecord(document.components);
  const componentSchemas = asRecord(components?.schemas) ?? {};
  const definitions = asRecord(document.definitions) ?? {};
  const schemas: ComponentSchema[] = [];
  for (const [prefix, entries] of [
    ["#/components/schemas", componentSchemas],
    ["#/definitions", definitions],
  ] as const) {
    for (const key of Object.keys(entries).sort()) {
      schemas.push({
        name: claimName(normalizeTypeName(key), usedNames),
        reference: `${prefix}/${escapeJsonPointer(key)}`,
        schema: entries[key],
      });
    }
  }
  return schemas;
}

function schemaToTypeScript(schema: unknown, context: TypeScriptSchemaContext): string {
  if (schema === undefined || schema === true) return "unknown";
  if (schema === false) return "never";
  const record = asRecord(schema);
  if (!record) return "unknown";

  const reference = typeof record.$ref === "string" ? record.$ref : undefined;
  if (reference) {
    const named = context.referenceNames.get(reference);
    if (named) return named;
    if (!context.references.has(reference) && reference.startsWith("#/")) {
      const target = resolvePointer(context.document, reference.slice(1));
      if (target !== undefined) {
        return schemaToTypeScript(target, {
          ...context,
          references: new Set(context.references).add(reference),
        });
      }
    }
    return "unknown";
  }

  if (Object.hasOwn(record, "const")) return literalType(record.const);
  if (Array.isArray(record.enum) && record.enum.length > 0) {
    return record.enum.map(literalType).join(" | ");
  }
  const allOf = schemaArray(record.allOf);
  if (allOf.length > 0) {
    return allOf.map((entry) => parenthesize(schemaToTypeScript(entry, context))).join(" & ");
  }
  const union = [...schemaArray(record.oneOf), ...schemaArray(record.anyOf)];
  if (union.length > 0) {
    return union.map((entry) => schemaToTypeScript(entry, context)).join(" | ");
  }

  const types = normalizeSchemaTypes(record.type);
  let result: string;
  if (types.length > 1) {
    result = types.map((type) => schemaTypeToTypeScript(type, record, context)).join(" | ");
  } else {
    result = schemaTypeToTypeScript(types[0], record, context);
  }
  if (record.nullable === true && !result.split(" | ").includes("null")) result += " | null";
  return result;
}

function schemaTypeToTypeScript(
  type: string | undefined,
  schema: Record<string, unknown>,
  context: TypeScriptSchemaContext,
): string {
  if (type === "string") return schema.format === "binary" ? "Blob" : "string";
  if (type === "integer" || type === "number") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "array" || schema.items !== undefined) {
    return `Array<${schemaToTypeScript(schema.items, context)}>`;
  }
  const properties = asRecord(schema.properties);
  if (type === "object" || properties || schema.additionalProperties !== undefined) {
    const required = new Set(stringArray(schema.required));
    const fields = Object.keys(properties ?? {})
      .sort()
      .map(
        (name) =>
          `${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${schemaToTypeScript(properties?.[name], context)}`,
      );
    const objectType = fields.length > 0 ? `{ ${fields.join("; ")} }` : "Record<string, never>";
    const additional = schema.additionalProperties;
    if (additional === false) return objectType;
    const additionalType =
      additional === undefined || additional === true
        ? "unknown"
        : schemaToTypeScript(additional, context);
    if (fields.length === 0) return `Record<string, ${additionalType}>`;
    return `${parenthesize(objectType)} & Record<string, ${additionalType}>`;
  }
  return "unknown";
}

function resolveSdkBaseUrl(override: string | undefined, servers: string[]): string {
  if (override) return override;
  for (const server of servers) {
    try {
      const url = new URL(server);
      if (url.protocol === "http:" || url.protocol === "https:") return url.href.replace(/\/$/, "");
    } catch {
      // Relative and templated servers require an explicit runtime base URL.
    }
  }
  return "";
}

function resolveOutputPath(rootDir: string, output: string): string {
  const outputPath = path.resolve(rootDir, output);
  if (!isPathInside(rootDir, outputPath)) {
    throw new Error("OpenAPI SDK output must be a file inside the project root.");
  }

  let existingAncestor = outputPath;
  while (!existsSync(existingAncestor)) {
    const parent = path.dirname(existingAncestor);
    if (parent === existingAncestor) break;
    existingAncestor = parent;
  }
  if (!isPathInside(realpathSync(rootDir), realpathSync(existingAncestor), true)) {
    throw new Error("OpenAPI SDK output must not escape the project root through a symlink.");
  }
  return outputPath;
}

function isPathInside(rootDir: string, candidate: string, allowRoot = false): boolean {
  const relative = path.relative(rootDir, candidate);
  return (
    (allowRoot || relative.length > 0) &&
    relative !== ".." &&
    !relative.startsWith(`..${path.sep}`) &&
    !path.isAbsolute(relative)
  );
}

function normalizeTypeName(value: string): string {
  const parts = value.match(/[A-Za-z0-9]+/g) ?? [];
  const name = parts.map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join("");
  const normalized = name || "ApiClient";
  return /^\d/.test(normalized) ? `_${normalized}` : normalized;
}

function normalizeMethodName(value: string): string {
  const typeName = normalizeTypeName(value);
  const methodName = `${typeName[0]?.toLowerCase() ?? "a"}${typeName.slice(1)}`;
  return RESERVED_METHOD_NAMES.has(methodName) ? `${methodName}Operation` : methodName;
}

function claimName(base: string, used: Set<string>): string {
  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) {
    candidate = `${base}${suffix}`;
    suffix += 1;
  }
  used.add(candidate);
  return candidate;
}

function normalizeSchemaTypes(value: unknown): string[] {
  if (typeof value === "string") return [value];
  return Array.isArray(value)
    ? value.filter((entry): entry is string => typeof entry === "string")
    : [];
}

function schemaArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((entry): entry is string => typeof entry === "string")
    : [];
}

function literalType(value: unknown): string {
  return typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    value === null
    ? JSON.stringify(value)
    : "unknown";
}

function parenthesize(value: string): string {
  return value.includes(" | ") || value.includes(" & ") ? `(${value})` : value;
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function resolvePointer(document: Record<string, unknown>, pointer: string): unknown {
  let current: unknown = document;
  for (const token of pointer.slice(1).split("/")) {
    const record = asRecord(current);
    if (!record) return undefined;
    current = record[token.replaceAll("~1", "/").replaceAll("~0", "~")];
  }
  return current;
}

function escapeJsonPointer(value: string): string {
  return value.replaceAll("~", "~0").replaceAll("/", "~1");
}

function normalizeRelativePath(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function sanitizeLineComment(value: string): string {
  return value.replace(/[\r\n]+/g, " ");
}
