packages:
  - "packages/astro"
  - "packages/astro-theme"
  - "packages/docs"
  - "packages/next"
  - "packages/fumadocs"
  - "packages/svelte"
  - "packages/svelte-theme"
  - "packages/nuxt"
  - "packages/nuxt-theme"
  - "examples/*"
  - "website"
