// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/next/api";

const handlers = createDocsAPI({
  entry: docsConfig.entry,
  contentDir: docsConfig.contentDir,
  i18n: docsConfig.i18n,
  changelog: docsConfig.changelog,
  search: docsConfig.search,
  ai: docsConfig.ai,
});

export async function GET(
  request: Request,
  { params }: { params: Promise<{ slug?: string[] }> },
) {
  const { slug = [] } = await params;
  const url = new URL(request.url);
  url.searchParams.set("format", "markdown");
  if (slug.length > 0) url.searchParams.set("path", slug.join("/"));
  else url.searchParams.delete("path");
  return handlers.GET(new Request(url, { headers: request.headers }));
}

export const revalidate = false;
