import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/api-reference.tsx",
    "src/client-callbacks.tsx",
    "src/config.ts",
    "src/layout.tsx",
    "src/mdx-plugins/remark-heading.ts",
    "src/mdx-plugins/rehype-toc.ts",
    "src/mdx-plugins/rehype-code.ts",
    "src/mdx-plugins/remark-og.ts",
  ],
  format: "esm",
  dts: true,
  clean: true,
  outDir: "dist",
  external: [
    "next",
    "react",
    "react-dom",
    "@/docs.config",
    "@farming-labs/theme/client-hooks",
    "@next/mdx",
    "@mdx-js/loader",
    "@mdx-js/react",
    "fumadocs-core",
    "fumadocs-openapi",
    "fumadocs-openapi/*",
    "fumadocs-ui",
    "fumadocs-ui/*",
    "remark-gfm",
    "remark-frontmatter",
    "remark-mdx-frontmatter",
  ],
});
