// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import DocsClientCallbacks from "@farming-labs/next/client-callbacks";
import { createDocsLayout, createDocsMetadata } from "@farming-labs/theme";

export const metadata = createDocsMetadata(docsConfig);
const DocsLayout = createDocsLayout(docsConfig);

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <DocsClientCallbacks />
      <DocsLayout>{children}</DocsLayout>
    </>
  );
}
