// Auto-generated by @farming-labs/next — do not edit manually.

import { NextRequest, NextResponse } from "next/server";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const pagePath = searchParams.get("path");
  if (!pagePath) {
    return NextResponse.json({ error: "Missing path parameter" }, { status: 400 });
  }

  // Sanitize: prevent directory traversal
  const sanitized = pagePath
    .replace(/\.\./g, "")
    .replace(/[^a-zA-Z0-9_\-\/]/g, "");

  const filePath = join(process.cwd(), "app", sanitized, "page.mdx");

  if (!existsSync(filePath)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const content = readFileSync(filePath, "utf-8");
  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
