// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import type { GeneratedChangelogEntry } from "@farming-labs/next/changelog";
import ChangelogEntry1 from "../../changelog/2026-04-15/page.mdx";
import ChangelogEntry2 from "../../changelog/2026-04-03/page.mdx";
import ChangelogEntry3 from "../../changelog/2026-03-18/page.mdx";
import {
  createNextChangelogEntryMetadata,
  createNextChangelogEntryPage,
  createNextChangelogStaticParams,
} from "@farming-labs/next/changelog";

export const changelogEntries: GeneratedChangelogEntry[] = [
  {
    slug: "2026-04-15",
    date: "2026-04-15",
    url: "/docs/changelogs/2026-04-15",
    sourcePath: "app/docs/changelog/2026-04-15/page.mdx",
    Component: ChangelogEntry1,
    metadata: {
      title: "API Reference: OpenAPI mode is now the default",
      description:
        "The Next example now ships with the faster OpenAPI experience, plus a tighter docs/API switcher.",
      image: "/images/changelog/fumadocs-openapi-mode.png",
      authors: ["Farming Labs"],
      version: "v0.1.13",
      tags: ["api-reference", "next"],
      pinned: true,
    },
  },
  {
    slug: "2026-04-03",
    date: "2026-04-03",
    url: "/docs/changelogs/2026-04-03",
    sourcePath: "app/docs/changelog/2026-04-03/page.mdx",
    Component: ChangelogEntry2,
    metadata: {
      title: "Colorful theme cleanup across docs and API routes",
      description:
        "We tightened the theme handoff so the colorful preset keeps its own identity when moving between docs and API reference.",
      image: "/images/changelog/colorful-theme-cleanup.png",
      authors: ["Farming Labs"],
      version: "v0.1.12",
      tags: ["themes", "colorful"],
    },
  },
  {
    slug: "2026-03-18",
    date: "2026-03-18",
    url: "/docs/changelogs/2026-03-18",
    sourcePath: "app/docs/changelog/2026-03-18/page.mdx",
    Component: ChangelogEntry3,
    metadata: {
      title: "Cloud page motion pass",
      description:
        "The cloud landing page picked up smoother looping motion, better path-based SVG behavior, and more stable theme controls.",
      image: "/images/changelog/cloud-motion-pass.png",
      authors: ["Farming Labs"],
      version: "v0.1.11",
      tags: ["cloud", "website"],
    },
  },
];

export const generateStaticParams = createNextChangelogStaticParams(changelogEntries);
export const generateMetadata = createNextChangelogEntryMetadata(docsConfig, changelogEntries);

const ChangelogEntryPage = createNextChangelogEntryPage(docsConfig, changelogEntries);

export default ChangelogEntryPage;
