// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { changelogEntries } from "../__changelog.generated";
import {
  createNextChangelogEntryMetadata,
  createNextChangelogEntryPage,
  createNextChangelogStaticParams,
} from "@farming-labs/next/changelog";

export const generateStaticParams = createNextChangelogStaticParams(changelogEntries);
export const generateMetadata = createNextChangelogEntryMetadata(docsConfig, changelogEntries);

const ChangelogEntryPage = createNextChangelogEntryPage(docsConfig, changelogEntries);

export default ChangelogEntryPage;
