/**
 * Unified docs API handler for @farming-labs/theme.
 *
 * A single route handler that serves **both** search and AI chat:
 *
 * - `GET  /api/docs?query=…` → full-text search over indexed MDX pages
 * - `POST /api/docs` → RAG-powered "Ask AI" (searches relevant docs,
 *   then streams an LLM response using the docs as context)
 *
 * This replaces the old `createDocsSearchAPI` — one handler, one route.
 *
 * @example
 * ```ts
 * // app/api/docs/route.ts (auto-generated by withDocs)
 * import { createDocsAPI } from "@farming-labs/next/api";
 * export const { GET, POST } = createDocsAPI();
 * export const revalidate = false;
 * ```
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { getNextAppDir } from "./get-app-dir.js";
import {
  normalizeDocsRelated,
  renderDocsRelatedMarkdownLines,
  resolveChangelogConfig,
  resolveDocsI18n,
  resolveDocsLocale,
} from "@farming-labs/docs";
import type {
  ChangelogConfig,
  DocsAgentFeedbackContext,
  DocsAgentFeedbackData,
  DocsI18nConfig,
  FeedbackConfig,
} from "@farming-labs/docs";
import {
  createDocsMcpHttpHandler,
  createFilesystemDocsMcpSource,
  resolveDocsMcpConfig,
  type DocsMcpPage,
} from "@farming-labs/docs/server";
import { performDocsSearch, resolveSearchRequestConfig } from "@farming-labs/docs";
import type {
  DocsMcpConfig,
  DocsSearchConfig,
  DocsSearchSourcePage,
  OrderingItem,
} from "@farming-labs/docs";
import { withLangInUrl } from "./i18n.js";

// ─── Types ──────────────────────────────────────────────────────────

interface AIProviderConfig {
  baseUrl: string;
  apiKey?: string;
}

interface AIModelEntry {
  id: string;
  label: string;
  provider?: string;
}

interface AIModelConfig {
  models?: AIModelEntry[];
  defaultModel?: string;
}

interface AIOptions {
  enabled?: boolean;
  model?: string | AIModelConfig;
  providers?: Record<string, AIProviderConfig>;
  systemPrompt?: string;
  /** Default baseUrl when no per-model provider is configured. */
  baseUrl?: string;
  /** Default apiKey when no per-model provider is configured. */
  apiKey?: string;
  maxResults?: number;
}

interface DocsAPIOptions {
  rootDir?: string;
  /** Docs entry folder (default: read from docs.config) */
  entry?: string;
  /** Override the docs content directory when it does not live in app/<entry>. */
  contentDir?: string;
  /** Changelog configuration. */
  changelog?: boolean | ChangelogConfig;
  /** Search language (default: "english") */
  language?: string;
  /** AI chat configuration */
  ai?: AIOptions;
  /** i18n config (optional) */
  i18n?: DocsI18nConfig;
  /** Search configuration */
  search?: boolean | DocsSearchConfig;
  /** Feedback configuration */
  feedback?: boolean | FeedbackConfig;
  /** MCP configuration used for the agent discovery spec. */
  mcp?: boolean | DocsMcpConfig;
}

interface DocsMCPAPIOptions {
  rootDir?: string;
  entry?: string;
  contentDir?: string;
  nav?: { title?: unknown };
  ordering?: "alphabetical" | "numeric" | OrderingItem[];
  mcp?: boolean | DocsMcpConfig;
  search?: boolean | DocsSearchConfig;
}

// ─── Helpers ────────────────────────────────────────────────────────

const FILE_EXTS = ["tsx", "ts", "jsx", "js"];
const DEFAULT_DOCS_API_ROUTE = "/api/docs";
const DEFAULT_AGENT_SPEC_ROUTE = "/api/docs/agent/spec";
const DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE = "/.well-known/agent";
const DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE = "/.well-known/agent.json";
const DEFAULT_MCP_ROUTE = "/api/docs/mcp";
const DEFAULT_MCP_PUBLIC_ROUTE = "/mcp";
const DEFAULT_MCP_WELL_KNOWN_ROUTE = "/.well-known/mcp";
const DEFAULT_LLMS_TXT_ROUTE = "/llms.txt";
const DEFAULT_LLMS_FULL_TXT_ROUTE = "/llms-full.txt";
const DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE = "/.well-known/llms.txt";
const DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE = "/.well-known/llms-full.txt";
const DEFAULT_AGENT_FEEDBACK_ROUTE = "/api/docs/agent/feedback";
const DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA: Record<string, unknown> = {
  type: "object",
  additionalProperties: false,
  properties: {
    task: {
      type: "string",
      description: "Short description of what the agent was trying to do.",
    },
    understanding: {
      type: "string",
      description: 'How well the docs supported the task, e.g. "partial" or "clear".',
    },
    outcome: {
      type: "string",
      description: 'What happened after reading the docs, e.g. "implemented" or "blocked".',
    },
    confidence: {
      type: "number",
      minimum: 0,
      maximum: 1,
      description: "Confidence score from 0 to 1.",
    },
    neededCodeReading: {
      type: "boolean",
      description: "Whether the agent still needed to inspect repository code.",
    },
    missingContext: {
      type: "array",
      items: { type: "string" },
      description: "Important details the docs did not provide clearly enough.",
    },
    docIssues: {
      type: "array",
      items: { type: "string" },
      description: "Specific documentation problems encountered during the task.",
    },
    suggestedImprovement: {
      type: "string",
      description: "Concrete suggestion for improving the docs page or examples.",
    },
  },
  required: ["task", "outcome"],
};

interface ResolvedAgentFeedbackConfig {
  enabled: boolean;
  route: string;
  schemaRoute: string;
  payloadSchema: Record<string, unknown>;
  schema: Record<string, unknown>;
  onFeedback?: (data: DocsAgentFeedbackData) => void | Promise<void>;
}

interface AgentFeedbackRequest {
  kind: "schema" | "submit";
}

interface AgentSpecOptions {
  origin: string;
  entry: string;
  i18n: ReturnType<typeof resolveDocsI18n>;
  search?: boolean | DocsSearchConfig;
  mcp: ReturnType<typeof resolveDocsMcpConfig>;
  feedback: ResolvedAgentFeedbackConfig;
  llms: LlmsTxtOptions & { enabled: boolean };
}

function normalizeAgentFeedbackRoute(
  route?: string,
  fallback = DEFAULT_AGENT_FEEDBACK_ROUTE,
): string {
  if (!route || route.trim().length === 0) return fallback;

  const normalized = `/${route}`.replace(/\/+/g, "/");
  return normalized !== "/" ? normalized.replace(/\/+$/, "") : fallback;
}

function buildAgentFeedbackSchema(payloadSchema: Record<string, unknown>): Record<string, unknown> {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      context: {
        type: "object",
        additionalProperties: false,
        properties: {
          page: { type: "string" },
          url: { type: "string" },
          slug: { type: "string" },
          locale: { type: "string" },
          source: { type: "string" },
        },
      },
      payload: payloadSchema,
    },
    required: ["payload"],
  };
}

function resolveAgentFeedbackConfig(
  feedback?: boolean | FeedbackConfig,
): ResolvedAgentFeedbackConfig {
  const route = normalizeAgentFeedbackRoute();
  const disabled = {
    enabled: false,
    route,
    schemaRoute: `${route}/schema`,
    payloadSchema: DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA,
    schema: buildAgentFeedbackSchema(DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA),
  } satisfies ResolvedAgentFeedbackConfig;

  if (!feedback || typeof feedback !== "object") return disabled;

  const agent = feedback.agent;
  if (!agent) return disabled;

  if (agent === true) {
    return {
      enabled: true,
      route,
      schemaRoute: `${route}/schema`,
      payloadSchema: DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA,
      schema: buildAgentFeedbackSchema(DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA),
    };
  }

  const resolvedRoute = normalizeAgentFeedbackRoute(agent.route, route);
  const resolvedSchemaRoute = normalizeAgentFeedbackRoute(
    agent.schemaRoute,
    `${resolvedRoute}/schema`,
  );

  const payloadSchema = agent.schema ?? DEFAULT_AGENT_FEEDBACK_PAYLOAD_SCHEMA;

  return {
    enabled: agent.enabled !== false,
    route: resolvedRoute,
    schemaRoute: resolvedSchemaRoute,
    payloadSchema,
    schema: buildAgentFeedbackSchema(payloadSchema),
    onFeedback: agent.onFeedback,
  };
}

function resolveAgentFeedbackRequest(
  url: URL,
  feedback: ResolvedAgentFeedbackConfig,
): AgentFeedbackRequest | null {
  if (!feedback.enabled) return null;

  const feedbackMode = url.searchParams.get("feedback")?.trim();
  const schemaMode = url.searchParams.get("schema")?.trim();
  if (feedbackMode === "agent") {
    return {
      kind: schemaMode === "1" || schemaMode === "true" ? "schema" : "submit",
    };
  }

  const pathname = normalizeUrlPath(url.pathname);
  if (pathname === feedback.schemaRoute) return { kind: "schema" };
  if (pathname === feedback.route) return { kind: "submit" };

  return null;
}

function resolveAgentSpecRequest(url: URL): boolean {
  if (url.searchParams.get("agent")?.trim() === "spec") return true;
  const pathname = normalizeUrlPath(url.pathname);
  return (
    pathname === DEFAULT_AGENT_SPEC_ROUTE ||
    pathname === DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE ||
    pathname === DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE
  );
}

function isSearchEnabled(search?: boolean | DocsSearchConfig): boolean {
  if (search === false) return false;
  if (search && typeof search === "object" && search.enabled === false) return false;
  return true;
}

function buildAgentSpec({ origin, entry, i18n, search, mcp, feedback, llms }: AgentSpecOptions) {
  const normalizedEntry = normalizePathSegment(entry) || "docs";
  const localesEnabled = i18n !== null;
  const searchEnabled = isSearchEnabled(search);

  return {
    version: "1",
    name: "@farming-labs/docs",
    baseUrl: origin,
    site: {
      title: llms.siteTitle ?? "Documentation",
      description: llms.siteDescription,
      entry: normalizedEntry,
      baseUrl: llms.baseUrl ?? origin,
    },
    locales: {
      enabled: localesEnabled,
      available: i18n?.locales ?? [],
      default: i18n?.defaultLocale ?? null,
      queryParam: "lang",
      fallbackQueryParam: "locale",
    },
    capabilities: {
      markdownRoutes: true,
      agentMdOverrides: true,
      agentBlocks: true,
      llms: llms.enabled,
      skills: true,
      mcp: mcp.enabled,
      search: searchEnabled,
      agentFeedback: feedback.enabled,
      locales: localesEnabled,
    },
    api: {
      docs: DEFAULT_DOCS_API_ROUTE,
      agentSpec: DEFAULT_AGENT_SPEC_ROUTE,
      agentSpecDefault: DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE,
      agentSpecFallback: DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE,
      agentSpecWellKnown: DEFAULT_AGENT_SPEC_WELL_KNOWN_ROUTE,
      agentSpecWellKnownJson: DEFAULT_AGENT_SPEC_WELL_KNOWN_JSON_ROUTE,
      agentSpecQuery: `${DEFAULT_DOCS_API_ROUTE}?agent=spec`,
    },
    // Always-on agent content surfaces. If these ever become configurable,
    // this spec must be wired to the same docs.config toggles instead of
    // continuing to report literal true values.
    markdown: {
      enabled: true,
      acceptHeader: "text/markdown",
      pagePattern: `/${normalizedEntry}/{slug}.md`,
      rootPage: `/${normalizedEntry}.md`,
      apiPattern: `${DEFAULT_DOCS_API_ROUTE}?format=markdown&path={slug}`,
      resolutionOrder: ["agent.md", "Agent blocks", "page markdown"],
    },
    llms: {
      enabled: llms.enabled,
      defaultTxt: DEFAULT_LLMS_TXT_ROUTE,
      defaultFull: DEFAULT_LLMS_FULL_TXT_ROUTE,
      txt: `${DEFAULT_DOCS_API_ROUTE}?format=llms`,
      full: `${DEFAULT_DOCS_API_ROUTE}?format=llms-full`,
      publicTxt: DEFAULT_LLMS_TXT_ROUTE,
      publicFull: DEFAULT_LLMS_FULL_TXT_ROUTE,
      wellKnownTxt: DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE,
      wellKnownFull: DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE,
    },
    search: {
      enabled: searchEnabled,
      endpoint: `${DEFAULT_DOCS_API_ROUTE}?query={query}`,
      method: "GET",
      queryParam: "query",
      localeParam: "lang",
    },
    // Skills metadata is bundled with this package today; there is no runtime
    // config switch for disabling it from the discovery spec.
    skills: {
      enabled: true,
      registry: "skills.sh",
      install: "npx skills add farming-labs/docs",
      recommended: [
        {
          name: "getting-started",
          description:
            "Use for installation, init, framework setup, theme CSS, and first docs.config wiring.",
        },
      ],
    },
    mcp: {
      enabled: mcp.enabled,
      endpoint: mcp.route,
      defaultEndpoint: DEFAULT_MCP_PUBLIC_ROUTE,
      publicEndpoint: DEFAULT_MCP_PUBLIC_ROUTE,
      wellKnownEndpoint: DEFAULT_MCP_WELL_KNOWN_ROUTE,
      publicEndpoints: [DEFAULT_MCP_PUBLIC_ROUTE, DEFAULT_MCP_WELL_KNOWN_ROUTE],
      canonicalEndpoint: DEFAULT_MCP_ROUTE,
      name: mcp.name,
      version: mcp.version,
      tools: mcp.tools,
    },
    feedback: {
      enabled: feedback.enabled,
      schema: feedback.schemaRoute,
      submit: feedback.route,
      schemaQuery: `${DEFAULT_DOCS_API_ROUTE}?feedback=agent&schema=1`,
      submitQuery: `${DEFAULT_DOCS_API_ROUTE}?feedback=agent`,
    },
    instructions: {
      preferMarkdownRoutes: true,
      useMcpWhenAvailable: true,
      readFeedbackSchemaBeforeSubmitting: true,
      doNotAssumeFeedbackPayloadShape: true,
    },
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeAgentFeedbackContext(value: unknown): DocsAgentFeedbackContext | undefined {
  if (!isPlainObject(value)) return undefined;

  const context: DocsAgentFeedbackContext = {};
  if (typeof value.page === "string") context.page = value.page;
  if (typeof value.url === "string") context.url = value.url;
  if (typeof value.slug === "string") context.slug = value.slug;
  if (typeof value.locale === "string") context.locale = value.locale;
  if (typeof value.source === "string") context.source = value.source;

  return Object.keys(context).length > 0 ? context : undefined;
}

async function parseAgentFeedbackData(
  request: Request,
): Promise<{ ok: true; data: DocsAgentFeedbackData } | { ok: false; response: Response }> {
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return {
      ok: false,
      response: Response.json({ error: "Agent feedback body must be valid JSON" }, { status: 400 }),
    };
  }

  if (!isPlainObject(body)) {
    return {
      ok: false,
      response: Response.json({ error: "Agent feedback body must be an object" }, { status: 400 }),
    };
  }

  if (!isPlainObject(body.payload)) {
    return {
      ok: false,
      response: Response.json(
        { error: "Agent feedback body must include a payload object" },
        { status: 400 },
      ),
    };
  }

  return {
    ok: true,
    data: {
      context: normalizeAgentFeedbackContext(body.context),
      payload: body.payload,
    },
  };
}

function validateAgentFeedbackPayload(
  value: unknown,
  schema: Record<string, unknown>,
  valuePath = "payload",
): string | undefined {
  const schemaType = typeof schema.type === "string" ? schema.type : undefined;

  if (Array.isArray(schema.enum) && !schema.enum.some((entry) => Object.is(entry, value))) {
    return `${valuePath} must be one of the configured enum values`;
  }

  if (schemaType === "object" || (!schemaType && (schema.properties || schema.required))) {
    if (!isPlainObject(value)) return `${valuePath} must be an object`;

    const properties = isPlainObject(schema.properties) ? schema.properties : {};
    const required = Array.isArray(schema.required)
      ? schema.required.filter((entry): entry is string => typeof entry === "string")
      : [];

    for (const key of required) {
      if (!(key in value)) return `${valuePath}.${key} is required`;
    }

    if (schema.additionalProperties === false) {
      for (const key of Object.keys(value)) {
        if (!(key in properties)) return `${valuePath}.${key} is not allowed`;
      }
    }

    for (const [key, propertySchema] of Object.entries(properties)) {
      if (!(key in value)) continue;
      if (!isPlainObject(propertySchema)) continue;

      const error = validateAgentFeedbackPayload(value[key], propertySchema, `${valuePath}.${key}`);
      if (error) return error;
    }

    return undefined;
  }

  if (schemaType === "array") {
    if (!Array.isArray(value)) return `${valuePath} must be an array`;
    if (!isPlainObject(schema.items)) return undefined;

    for (const [index, item] of value.entries()) {
      const error = validateAgentFeedbackPayload(item, schema.items, `${valuePath}[${index}]`);
      if (error) return error;
    }

    return undefined;
  }

  if (schemaType === "string") {
    if (typeof value !== "string") return `${valuePath} must be a string`;

    if (typeof schema.minLength === "number" && value.length < schema.minLength) {
      return `${valuePath} must be at least ${schema.minLength} characters`;
    }

    if (typeof schema.maxLength === "number" && value.length > schema.maxLength) {
      return `${valuePath} must be at most ${schema.maxLength} characters`;
    }

    return undefined;
  }

  if (schemaType === "number") {
    if (typeof value !== "number" || !Number.isFinite(value))
      return `${valuePath} must be a number`;

    if (typeof schema.minimum === "number" && value < schema.minimum) {
      return `${valuePath} must be >= ${schema.minimum}`;
    }

    if (typeof schema.maximum === "number" && value > schema.maximum) {
      return `${valuePath} must be <= ${schema.maximum}`;
    }

    return undefined;
  }

  if (schemaType === "boolean") {
    if (typeof value !== "boolean") return `${valuePath} must be a boolean`;
    return undefined;
  }

  return undefined;
}

function readEntry(root: string): string {
  for (const ext of FILE_EXTS) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (fs.existsSync(configPath)) {
      try {
        const content = fs.readFileSync(configPath, "utf-8");
        const match = content.match(/entry\s*:\s*["']([^"']+)["']/);
        if (match) return match[1];
      } catch {
        // fall through
      }
    }
  }
  return "docs";
}

function readI18nConfig(root: string): DocsI18nConfig | null {
  for (const ext of FILE_EXTS) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (!fs.existsSync(configPath)) continue;
    try {
      const content = fs.readFileSync(configPath, "utf-8");
      if (!content.includes("i18n")) continue;

      const localesMatch = content.match(/i18n\s*:\s*\{[\s\S]*?locales\s*:\s*\[([^\]]+)\]/);
      if (!localesMatch) continue;

      const locales = localesMatch[1]
        .split(",")
        .map((l) => l.trim().replace(/^['"`]|['"`]$/g, ""))
        .filter(Boolean);
      if (locales.length === 0) continue;

      const defaultLocaleMatch = content.match(
        /i18n\s*:\s*\{[\s\S]*?defaultLocale\s*:\s*["']([^"']+)["']/,
      );

      return {
        locales,
        defaultLocale: defaultLocaleMatch?.[1],
      };
    } catch {
      // fall through
    }
  }
  return null;
}

/**
 * Read AI config from docs.config by parsing the file for the `ai` block.
 * This avoids importing the config (which may use JSX/React).
 */
function readAIConfig(root: string): AIOptions {
  for (const ext of FILE_EXTS) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (fs.existsSync(configPath)) {
      try {
        const content = fs.readFileSync(configPath, "utf-8");

        // Check if AI is enabled
        if (!content.includes("ai:") && !content.includes("ai :")) {
          return {};
        }

        const enabledMatch = content.match(/ai\s*:\s*\{[^}]*enabled\s*:\s*(true|false)/s);
        if (enabledMatch && enabledMatch[1] === "false") return {};

        const modelMatch = content.match(/ai\s*:\s*\{[^}]*model\s*:\s*["']([^"']+)["']/s);
        const baseUrlMatch = content.match(/ai\s*:\s*\{[^}]*baseUrl\s*:\s*["']([^"']+)["']/s);
        // Match `apiKey: process.env.SOME_VAR` and resolve it at runtime
        const apiKeyMatch = content.match(/ai\s*:\s*\{[^}]*apiKey\s*:\s*process\.env\.(\w+)/s);
        const maxResultsMatch = content.match(/ai\s*:\s*\{[^}]*maxResults\s*:\s*(\d+)/s);
        const systemPromptMatch = content.match(
          /ai\s*:\s*\{[^}]*systemPrompt\s*:\s*["'`]([^"'`]+)["'`]/s,
        );

        return {
          enabled: true,
          model: modelMatch?.[1],
          baseUrl: baseUrlMatch?.[1],
          apiKey: apiKeyMatch?.[1] ? process.env[apiKeyMatch[1]] : undefined,
          maxResults: maxResultsMatch ? parseInt(maxResultsMatch[1], 10) : undefined,
          systemPrompt: systemPromptMatch?.[1],
        };
      } catch {
        // fall through
      }
    }
  }
  return {};
}

function readMcpConfig(root: string): boolean | DocsMcpConfig | undefined {
  for (const ext of FILE_EXTS) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (!fs.existsSync(configPath)) continue;

    try {
      const content = fs.readFileSync(configPath, "utf-8");
      const sanitized = stripCommentsAndStrings(content);
      const configObject = extractRootConfigObject(content, sanitized);
      const scopedContent = configObject?.content ?? content;
      const scopedSanitized = configObject?.sanitized ?? sanitized;

      const booleanValue = readTopLevelBoolean(scopedSanitized, "mcp");
      if (booleanValue !== undefined) return booleanValue;

      const block = extractObjectLiteral(scopedContent, scopedSanitized, "mcp");
      if (!block) continue;

      return {
        enabled: readBooleanFromBlock(block, "enabled"),
        route: readStringFromBlock(block, "route"),
        name: readStringFromBlock(block, "name"),
        version: readStringFromBlock(block, "version"),
        tools: {
          listPages: readBooleanFromBlock(block, "listPages"),
          readPage: readBooleanFromBlock(block, "readPage"),
          searchDocs: readBooleanFromBlock(block, "searchDocs"),
          getNavigation: readBooleanFromBlock(block, "getNavigation"),
        },
      };
    } catch {
      // fall through
    }
  }

  return undefined;
}

function readStringFromBlock(block: string, key: string): string | undefined {
  const match = block.match(new RegExp(`${key}\\s*:\\s*["']([^"']+)["']`));
  return match?.[1];
}

function readBooleanFromBlock(block: string, key: string): boolean | undefined {
  const match = block.match(new RegExp(`${key}\\s*:\\s*(true|false)`));
  return match ? match[1] === "true" : undefined;
}

function extractObjectLiteral(content: string, sanitized: string, key: string): string | undefined {
  const keyIndex = findTopLevelPropertyIndex(sanitized, key);
  if (keyIndex === -1) return undefined;

  const colonIndex = sanitized.indexOf(":", keyIndex + key.length);
  if (colonIndex === -1) return undefined;

  const braceStart = sanitized.indexOf("{", colonIndex);
  if (braceStart === -1) return undefined;

  let depth = 0;

  for (let index = braceStart; index < sanitized.length; index += 1) {
    const char = sanitized[index];

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char !== "}") continue;

    depth -= 1;
    if (depth === 0) {
      return content.slice(braceStart + 1, index);
    }
  }

  return undefined;
}

function readTopLevelBoolean(content: string, key: string): boolean | undefined {
  const keyIndex = findTopLevelPropertyIndex(content, key);
  if (keyIndex === -1) return undefined;

  const match = content.slice(keyIndex + key.length).match(/^\s*:\s*(true|false)\b/);
  if (!match) return undefined;
  return match[1] === "true";
}

function findTopLevelPropertyIndex(content: string, key: string): number {
  let depth = 0;

  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char === "}") {
      depth = Math.max(0, depth - 1);
      continue;
    }

    if (depth !== 0) continue;
    if (!content.startsWith(key, index)) continue;

    const previous = index === 0 ? "" : content[index - 1];
    if (previous && /[\w$]/.test(previous)) continue;

    const next = content[index + key.length] ?? "";
    if (next && /[\w$]/.test(next)) continue;

    const afterKey = content.slice(index + key.length);
    if (!afterKey.match(/^\s*:/)) continue;

    return index;
  }

  return -1;
}

function extractRootConfigObject(
  content: string,
  sanitized: string,
): { content: string; sanitized: string } | undefined {
  const defineDocsIndex = sanitized.indexOf("defineDocs");
  const exportDefaultIndex = sanitized.indexOf("export default");

  let braceStart = -1;

  if (defineDocsIndex !== -1) {
    const parenIndex = sanitized.indexOf("(", defineDocsIndex);
    if (parenIndex !== -1) {
      braceStart = sanitized.indexOf("{", parenIndex);
    }
  }

  if (braceStart === -1 && exportDefaultIndex !== -1) {
    braceStart = sanitized.indexOf("{", exportDefaultIndex);
  }

  if (braceStart === -1) return undefined;

  let depth = 0;

  for (let index = braceStart; index < sanitized.length; index += 1) {
    const char = sanitized[index];

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char !== "}") continue;

    depth -= 1;
    if (depth === 0) {
      return {
        content: content.slice(braceStart + 1, index),
        sanitized: sanitized.slice(braceStart + 1, index),
      };
    }
  }

  return undefined;
}

function stripCommentsAndStrings(content: string): string {
  let result = "";
  let index = 0;
  let state:
    | "normal"
    | "singleQuote"
    | "doubleQuote"
    | "template"
    | "lineComment"
    | "blockComment" = "normal";

  while (index < content.length) {
    const char = content[index];
    const next = content[index + 1];

    if (state === "lineComment") {
      if (char === "\n") {
        state = "normal";
        result += "\n";
      } else {
        result += " ";
      }
      index += 1;
      continue;
    }

    if (state === "blockComment") {
      if (char === "*" && next === "/") {
        result += "  ";
        index += 2;
        state = "normal";
      } else {
        result += char === "\n" ? "\n" : " ";
        index += 1;
      }
      continue;
    }

    if (state === "singleQuote" || state === "doubleQuote" || state === "template") {
      const quote = state === "singleQuote" ? "'" : state === "doubleQuote" ? '"' : "`";

      if (char === "\\") {
        result += " ";
        if (next) result += next === "\n" ? "\n" : " ";
        index += 2;
        continue;
      }

      result += char === "\n" ? "\n" : " ";

      if (char === quote) {
        state = "normal";
      }

      index += 1;
      continue;
    }

    if (char === "/" && next === "/") {
      result += "  ";
      index += 2;
      state = "lineComment";
      continue;
    }

    if (char === "/" && next === "*") {
      result += "  ";
      index += 2;
      state = "blockComment";
      continue;
    }

    if (char === "'") {
      result += " ";
      index += 1;
      state = "singleQuote";
      continue;
    }

    if (char === '"') {
      result += " ";
      index += 1;
      state = "doubleQuote";
      continue;
    }

    if (char === "`") {
      result += " ";
      index += 1;
      state = "template";
      continue;
    }

    result += char;
    index += 1;
  }

  return result;
}

function resolveAgentMdxContent(content: string, audience: "human" | "agent"): string {
  const lines = content.split("\n");
  const output: string[] = [];
  let fenceMarker: string | null = null;
  let agentDepth = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);

    if (fenceMatch) {
      if (!fenceMarker) {
        fenceMarker = fenceMatch[1];
      } else if (trimmed.startsWith(fenceMarker)) {
        fenceMarker = null;
      }

      if (audience === "agent" || agentDepth === 0) {
        output.push(line);
      }
      continue;
    }

    if (!fenceMarker) {
      if (/^<Agent(?:\s[^>]*)?\/>$/.test(trimmed)) {
        continue;
      }

      const singleLineMatch = line.match(/^(\s*)<Agent(?:\s[^>]*)?>([\s\S]*?)<\/Agent>\s*$/);
      if (singleLineMatch) {
        if (audience === "agent" && singleLineMatch[2]) {
          output.push(`${singleLineMatch[1]}${singleLineMatch[2]}`);
        }
        continue;
      }

      const openMatch = line.match(/^(\s*)<Agent(?:\s[^>]*)?>\s*$/);
      if (openMatch) {
        agentDepth += 1;
        continue;
      }

      const openWithContentMatch = line.match(/^(\s*)<Agent(?:\s[^>]*)?>(.*)$/);
      if (openWithContentMatch) {
        agentDepth += 1;
        if (audience === "agent" && openWithContentMatch[2]) {
          output.push(`${openWithContentMatch[1]}${openWithContentMatch[2]}`);
        }
        continue;
      }

      const closeWithContentMatch = line.match(/^(.*)<\/Agent>\s*$/);
      if (closeWithContentMatch && agentDepth > 0) {
        if (audience === "agent" && closeWithContentMatch[1]) {
          output.push(closeWithContentMatch[1]);
        }
        agentDepth = Math.max(0, agentDepth - 1);
        continue;
      }

      if (/^<\/Agent>\s*$/.test(trimmed) && agentDepth > 0) {
        agentDepth = Math.max(0, agentDepth - 1);
        continue;
      }
    }

    if (agentDepth > 0 && audience === "human") {
      continue;
    }

    output.push(line);
  }

  return output
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function stripMdx(content: string): string {
  return content
    .replace(/^(import|export)\s.*$/gm, "")
    .replace(/<[^>]+\/>/g, "")
    .replace(/<\/?[A-Z][^>]*>/g, "")
    .replace(/<\/?[a-z][^>]*>/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/(\*{1,3}|_{1,3})(.*?)\1/g, "$2")
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^>\s+/gm, "")
    .replace(/^[-*_]{3,}\s*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function scanDocsDir(
  docsDir: string,
  entry: string,
  locale?: string,
  excludedDirs: string[] = [],
): DocsSearchSourcePage[] {
  const indexes: Array<DocsSearchSourcePage & { relatedInput?: unknown }> = [];

  function isExcluded(dir: string) {
    const resolved = path.resolve(dir);
    return excludedDirs.some((excluded) => {
      const relative = path.relative(excluded, resolved);
      return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
    });
  }

  function scan(dir: string, slugParts: string[]) {
    if (!fs.existsSync(dir)) return;
    if (isExcluded(dir)) return;

    const pagePath = path.join(dir, "page.mdx");
    if (fs.existsSync(pagePath)) {
      try {
        const raw = fs.readFileSync(pagePath, "utf-8");
        const { data } = matter(raw);
        const title =
          (data.title as string) ||
          slugParts[slugParts.length - 1]?.replace(/-/g, " ") ||
          "Documentation";
        const description = data.description as string | undefined;
        const { content: fileContent } = matter(raw);
        const rawContent = resolveAgentMdxContent(fileContent, "human");
        const agentRawContent = resolveAgentMdxContent(fileContent, "agent");
        const content = stripMdx(rawContent);
        const baseUrl = slugParts.length === 0 ? `/${entry}` : `/${entry}/${slugParts.join("/")}`;
        const url = withLangInUrl(baseUrl, locale);

        indexes.push({
          title,
          description,
          relatedInput: data.related,
          content,
          rawContent,
          agentFallbackRawContent: agentRawContent !== rawContent ? agentRawContent : undefined,
          url,
          locale,
        });
      } catch {
        // skip unreadable files
      }
    }

    let entries: string[];
    try {
      entries = fs.readdirSync(dir);
    } catch {
      return;
    }

    for (const name of entries.sort()) {
      const full = path.join(dir, name);
      try {
        if (fs.statSync(full).isDirectory()) {
          scan(full, [...slugParts, name]);
        }
      } catch {
        // skip
      }
    }
  }

  scan(docsDir, []);
  return resolveRelatedForSearchPages(indexes);
}

function scanChangelogDir(
  changelogDir: string,
  entryPath: string,
  changelogPath: string,
  locale?: string,
): DocsSearchSourcePage[] {
  if (!fs.existsSync(changelogDir)) return [];

  const indexes: Array<DocsSearchSourcePage & { relatedInput?: unknown }> = [];
  let entries: string[];

  try {
    entries = fs.readdirSync(changelogDir).sort().reverse();
  } catch {
    return indexes;
  }

  for (const name of entries) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(name)) continue;
    const entryDir = path.join(changelogDir, name);
    let isDirectory = false;

    try {
      isDirectory = fs.existsSync(entryDir) && fs.statSync(entryDir).isDirectory();
    } catch {
      continue;
    }

    if (!isDirectory) continue;

    const pagePath = path.join(entryDir, "page.mdx");
    if (!fs.existsSync(pagePath)) continue;

    try {
      const raw = fs.readFileSync(pagePath, "utf-8");
      const { data, content: fileContent } = matter(raw);
      if (data.draft === true) continue;

      const title = (data.title as string) || name.replace(/-/g, " ");
      const description = data.description as string | undefined;
      const rawContent = resolveAgentMdxContent(fileContent, "human");
      const agentRawContent = resolveAgentMdxContent(fileContent, "agent");
      const content = stripMdx(rawContent);
      const url = withLangInUrl(`/${entryPath}/${changelogPath}/${name}`, locale);
      const tags = Array.isArray(data.tags)
        ? data.tags.filter((value): value is string => typeof value === "string")
        : undefined;

      indexes.push({
        title,
        description,
        relatedInput: data.related,
        content,
        rawContent,
        agentFallbackRawContent: agentRawContent !== rawContent ? agentRawContent : undefined,
        url,
        locale,
        type: "changelog",
        version: typeof data.version === "string" ? data.version : undefined,
        tags,
      });
    } catch {
      // skip unreadable files
    }
  }

  return resolveRelatedForSearchPages(indexes);
}

function resolveRelatedForSearchPages(
  pages: Array<DocsSearchSourcePage & { relatedInput?: unknown }>,
): DocsSearchSourcePage[] {
  return pages.map(({ relatedInput, ...page }) => {
    const related = normalizeDocsRelated(relatedInput);
    return related.length > 0 ? { ...page, related } : page;
  });
}

function normalizePathSegment(value: string): string {
  return value.replace(/^\/+|\/+$/g, "");
}

function normalizeUrlPath(value: string): string {
  const normalized = value.replace(/\/+/g, "/");
  if (normalized === "/") return normalized;
  return normalized.replace(/\/+$/, "");
}

function normalizeRequestedMarkdownPath(entry: string, requestedPath: string): string {
  const trimmed = requestedPath.trim().replace(/\.md$/i, "");
  if (!trimmed) return `/${entry}`;

  const normalized = normalizeUrlPath(trimmed.startsWith("/") ? trimmed : `/${trimmed}`);
  const normalizedEntry = `/${normalizePathSegment(entry)}`;
  if (normalized === normalizedEntry || normalized.startsWith(`${normalizedEntry}/`)) {
    return normalized;
  }

  const slug = normalizePathSegment(trimmed);
  return slug ? normalizeUrlPath(`${normalizedEntry}/${slug}`) : normalizedEntry;
}

function findDocsMcpPage(
  entry: string,
  pages: DocsMcpPage[],
  requestedPath: string,
): DocsMcpPage | null {
  const normalizedRequest = normalizeRequestedMarkdownPath(entry, requestedPath);

  for (const page of pages) {
    if (normalizeUrlPath(page.url) === normalizedRequest) return page;
  }

  const normalizedSlug = normalizePathSegment(
    requestedPath.replace(/^\//, "").replace(/\.md$/i, ""),
  );
  for (const page of pages) {
    if (normalizePathSegment(page.slug) === normalizedSlug) return page;
  }

  return null;
}

function acceptsMarkdown(request: Request): boolean {
  const accept = request.headers.get("accept");
  if (!accept) return false;
  return accept
    .split(",")
    .map((value) => value.trim())
    .some((value) => {
      const [mediaType, ...params] = value.split(";").map((part) => part.trim().toLowerCase());
      if (mediaType !== "text/markdown") return false;

      const qualityParam = params.find((param) => param.split("=", 1)[0]?.trim() === "q");
      if (!qualityParam) return true;

      const qualityValue = qualityParam.slice(qualityParam.indexOf("=") + 1).trim();
      const quality = Number.parseFloat(qualityValue);
      return Number.isFinite(quality) ? quality > 0 : true;
    });
}

function resolveMarkdownRequest(
  entry: string,
  url: URL,
  request: Request,
): { requestedPath: string } | null {
  const format = url.searchParams.get("format")?.trim();
  if (format === "markdown") {
    return {
      requestedPath: url.searchParams.get("path")?.trim() ?? "",
    };
  }

  const pathname = normalizeUrlPath(url.pathname);
  const normalizedEntry = `/${normalizePathSegment(entry)}`;

  if (pathname === `${normalizedEntry}.md`) {
    return { requestedPath: "" };
  }

  const slugPrefix = `${normalizedEntry}/`;
  if (pathname.startsWith(slugPrefix) && pathname.endsWith(".md")) {
    return {
      requestedPath: pathname.slice(slugPrefix.length, -3),
    };
  }

  if (acceptsMarkdown(request)) {
    if (pathname === normalizedEntry) {
      return { requestedPath: "" };
    }

    if (pathname.startsWith(slugPrefix)) {
      return {
        requestedPath: pathname.slice(slugPrefix.length),
      };
    }
  }

  return null;
}

function resolveLlmsTxtFormat(url: URL): "llms" | "llms-full" | null {
  const pathname = normalizeUrlPath(url.pathname);

  if (pathname === DEFAULT_LLMS_TXT_ROUTE || pathname === DEFAULT_LLMS_TXT_WELL_KNOWN_ROUTE) {
    return "llms";
  }

  if (
    pathname === DEFAULT_LLMS_FULL_TXT_ROUTE ||
    pathname === DEFAULT_LLMS_FULL_TXT_WELL_KNOWN_ROUTE
  ) {
    return "llms-full";
  }

  const format = url.searchParams.get("format");
  return format === "llms" || format === "llms-full" ? format : null;
}

function renderMarkdownDocument(page: DocsMcpPage | DocsSearchSourcePage): string {
  const relatedLines = renderDocsRelatedMarkdownLines(page.related);
  if (
    "agentRawContent" in page &&
    page.agentRawContent !== undefined &&
    relatedLines.length === 0
  ) {
    return page.agentRawContent;
  }

  const lines = [`# ${page.title}`, `URL: ${page.url}`];
  if (page.description) lines.push(`Description: ${page.description}`);
  lines.push(...relatedLines);
  lines.push(
    "",
    page.agentRawContent ?? page.agentFallbackRawContent ?? page.rawContent ?? page.content,
  );
  return lines.join("\n");
}

// ─── AI Chat (RAG) ─────────────────────────────────────────────────

const DEFAULT_SYSTEM_PROMPT = `You are a helpful documentation assistant. Answer questions based on the provided documentation context. Be concise and accurate. If the answer is not in the context, say so honestly. Use markdown formatting for code examples and links.`;

interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

function resolveModelAndProvider(
  aiConfig: AIOptions,
  requestedModelId?: string,
): { model: string; baseUrl: string; apiKey: string | undefined } {
  const raw = aiConfig.model as AIModelConfig | string | undefined;

  // Find the model list (from nested or flat config)
  const modelList: AIModelEntry[] = (typeof raw === "object" && raw?.models) || [];

  // Resolve model id
  let modelId = requestedModelId;
  if (!modelId) {
    if (typeof raw === "string") modelId = raw;
    else if (typeof raw === "object") modelId = raw.defaultModel ?? raw.models?.[0]?.id;
    if (!modelId) modelId = "gpt-4o-mini";
  }

  // Find matching model entry to get its provider key
  const entry = modelList.find((m) => m.id === modelId);
  const providerKey = entry?.provider;

  // Resolve provider config
  const providerConfig = providerKey && aiConfig.providers?.[providerKey];

  const baseUrl = (
    (providerConfig && providerConfig.baseUrl) ||
    aiConfig.baseUrl ||
    "https://api.openai.com/v1"
  ).replace(/\/$/, "");

  const apiKey =
    (providerConfig && providerConfig.apiKey) || aiConfig.apiKey || process.env.OPENAI_API_KEY;

  return { model: modelId, baseUrl, apiKey };
}

async function handleAskAI(
  request: Request,
  indexes: DocsSearchSourcePage[],
  aiConfig: AIOptions,
): Promise<Response> {
  // ── Parse request ──────────────────────────────────────────────
  let body: { messages?: ChatMessage[]; model?: string };
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: "Invalid JSON body. Expected { messages: [...] }" },
      { status: 400 },
    );
  }

  const messages = body.messages;
  if (!Array.isArray(messages) || messages.length === 0) {
    return Response.json(
      { error: "messages array is required and must not be empty." },
      { status: 400 },
    );
  }

  const lastUserMessage = [...messages].reverse().find((m) => m.role === "user");
  if (!lastUserMessage) {
    return Response.json({ error: "At least one user message is required." }, { status: 400 });
  }

  // ── Search for relevant docs (RAG retrieval) ───────────────────
  const maxResults = aiConfig.maxResults ?? 5;
  const query = lastUserMessage.content;

  // Use the in-memory index for fast context retrieval
  const scored = indexes
    .map((doc) => {
      const q = query.toLowerCase();
      const titleMatch = doc.title.toLowerCase().includes(q) ? 10 : 0;
      const contentWords = q.split(/\s+/);
      const contentMatch = contentWords.reduce((score, word) => {
        return score + (doc.content.toLowerCase().includes(word) ? 1 : 0);
      }, 0);
      return { ...doc, score: titleMatch + contentMatch };
    })
    .filter((d) => d.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, maxResults);

  // Build context from relevant docs
  const contextParts = scored.map(
    (doc) =>
      `## ${doc.title}\nURL: ${doc.url}\n${doc.description ? `Description: ${doc.description}\n` : ""}\n${doc.content}`,
  );
  const context = contextParts.join("\n\n---\n\n");

  // ── Build LLM messages ─────────────────────────────────────────
  const systemPrompt = aiConfig.systemPrompt ?? DEFAULT_SYSTEM_PROMPT;
  const systemMessage: ChatMessage = {
    role: "system",
    content: context
      ? `${systemPrompt}\n\n---\n\nDocumentation context:\n\n${context}`
      : systemPrompt,
  };

  const llmMessages: ChatMessage[] = [
    systemMessage,
    ...messages.filter((m) => m.role !== "system"),
  ];

  // ── Resolve model + provider ────────────────────────────────────
  const requestedModel =
    typeof body.model === "string" && body.model.trim().length > 0 ? body.model.trim() : undefined;

  const resolved = resolveModelAndProvider(aiConfig, requestedModel);

  if (!resolved.apiKey) {
    return Response.json(
      {
        error: `AI is enabled but no API key was found. Either set apiKey in your docs.config ai section, configure a provider, or add OPENAI_API_KEY to your .env.local file.`,
      },
      { status: 500 },
    );
  }

  const llmResponse = await fetch(`${resolved.baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resolved.apiKey}`,
    },
    body: JSON.stringify({
      model: resolved.model,
      stream: true,
      messages: llmMessages,
    }),
  });

  if (!llmResponse.ok) {
    const errText = await llmResponse.text().catch(() => "Unknown error");
    return Response.json(
      { error: `LLM API error (${llmResponse.status}): ${errText}` },
      { status: 502 },
    );
  }

  // Proxy the SSE stream directly to the client
  return new Response(llmResponse.body, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}

// ─── llms.txt generation ────────────────────────────────────────────

interface LlmsTxtOptions {
  siteTitle?: string;
  siteDescription?: string;
  baseUrl?: string;
}

function readLlmsTxtConfig(root: string): LlmsTxtOptions & { enabled: boolean } {
  for (const ext of FILE_EXTS) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (fs.existsSync(configPath)) {
      try {
        const content = fs.readFileSync(configPath, "utf-8");

        if (!content.includes("llmsTxt")) return { enabled: false };

        const isBoolTrue = /llmsTxt\s*:\s*true/.test(content);
        if (isBoolTrue) return { enabled: true };

        const enabledMatch = content.match(/llmsTxt\s*:\s*\{[^}]*enabled\s*:\s*(true|false)/s);
        if (enabledMatch && enabledMatch[1] === "false") return { enabled: false };

        const baseUrlMatch = content.match(/llmsTxt\s*:\s*\{[^}]*baseUrl\s*:\s*["']([^"']+)["']/s);
        const siteTitleMatch = content.match(
          /llmsTxt\s*:\s*\{[^}]*siteTitle\s*:\s*["']([^"']+)["']/s,
        );
        const siteDescMatch = content.match(
          /llmsTxt\s*:\s*\{[^}]*siteDescription\s*:\s*["']([^"']+)["']/s,
        );

        const navTitleMatch = content.match(/nav\s*:\s*\{[^}]*title\s*:\s*["']([^"']+)["']/s);

        return {
          enabled: true,
          baseUrl: baseUrlMatch?.[1],
          siteTitle: siteTitleMatch?.[1] ?? navTitleMatch?.[1],
          siteDescription: siteDescMatch?.[1],
        };
      } catch {
        // fall through
      }
    }
  }
  return { enabled: false };
}

function generateLlmsTxt(
  indexes: DocsSearchSourcePage[],
  options: LlmsTxtOptions,
): { llmsTxt: string; llmsFullTxt: string } {
  const { siteTitle = "Documentation", siteDescription, baseUrl = "" } = options;

  let llmsTxt = `# ${siteTitle}\n\n`;
  if (siteDescription) llmsTxt += `> ${siteDescription}\n\n`;
  llmsTxt += `## Pages\n\n`;
  for (const page of indexes) {
    llmsTxt += `- [${page.title}](${baseUrl}${page.url})`;
    if (page.description) llmsTxt += `: ${page.description}`;
    llmsTxt += `\n`;
  }

  let llmsFullTxt = `# ${siteTitle}\n\n`;
  if (siteDescription) llmsFullTxt += `> ${siteDescription}\n\n`;
  for (const page of indexes) {
    llmsFullTxt += `## ${page.title}\n\n`;
    llmsFullTxt += `URL: ${baseUrl}${page.url}\n\n`;
    if (page.description) llmsFullTxt += `${page.description}\n\n`;
    llmsFullTxt += `${page.content}\n\n---\n\n`;
  }

  return { llmsTxt, llmsFullTxt };
}

// ─── createDocsAPI ──────────────────────────────────────────────────

/**
 * Create a unified docs API route handler.
 *
 * Returns `{ GET, POST }` for use in a Next.js route handler:
 * - **GET  ?query=…**        → full-text search
 * - **GET  ?format=llms**     → llms.txt (concise page listing)
 * - **GET  ?format=llms-full** → llms-full.txt (full page content)
 * - **POST**                  → AI-powered chat with RAG
 *
 * @example
 * ```ts
 * // app/api/docs/route.ts (auto-generated by withDocs)
 * import { createDocsAPI } from "@farming-labs/next/api";
 * export const { GET, POST } = createDocsAPI();
 * export const revalidate = false;
 * ```
 *
 * @param options - Optional overrides (entry, language, ai config)
 */
/**
 * @deprecated Prefer `createDocsAPI` from `@farming-labs/next/api` in Next.js apps.
 * The `@farming-labs/theme/api` path is kept for compatibility and will be phased out.
 */
export function createDocsAPI(options?: DocsAPIOptions) {
  const root = options?.rootDir ?? process.cwd();
  const entry = options?.entry ?? readEntry(root);
  const appDir = getNextAppDir(root);
  const contentDir = options?.contentDir ?? path.join(appDir, entry);
  const changelogConfig = resolveChangelogConfig(options?.changelog);
  const agentFeedbackConfig = resolveAgentFeedbackConfig(options?.feedback);

  const i18nConfig = options?.i18n ?? readI18nConfig(root);
  const i18n = resolveDocsI18n(i18nConfig);

  // Read AI config from docs.config if not explicitly provided
  const aiConfig: AIOptions = options?.ai ?? readAIConfig(root);
  const searchConfig = options?.search;

  // Read llms.txt config
  const llmsConfig = readLlmsTxtConfig(root);
  const mcpConfig = resolveDocsMcpConfig(options?.mcp ?? readMcpConfig(root), {
    defaultName: llmsConfig.siteTitle ?? "Documentation",
  });

  type DocsContext = {
    entryPath: string;
    docsDirs: string[];
    changelogDirs: string[];
    locale?: string;
  };

  function resolveDocsDirCandidates(locale?: string): string[] {
    const relativeCandidates = new Set<string>();

    if (path.isAbsolute(contentDir)) {
      return [locale ? path.join(contentDir, locale) : contentDir];
    }

    relativeCandidates.add(contentDir);
    relativeCandidates.add(path.join("app", entry));
    relativeCandidates.add(path.join("src", "app", entry));

    const rootCandidates = new Set<string>([root]);
    rootCandidates.add(process.cwd());
    if (path.basename(root) === "server") {
      rootCandidates.add(path.resolve(root, "..", ".."));
    } else {
      rootCandidates.add(path.join(root, ".next", "server"));
      rootCandidates.add(path.join(root, ".next-build", "server"));
    }

    const resolved = new Set<string>();
    for (const base of rootCandidates) {
      for (const relative of relativeCandidates) {
        const candidate = path.join(base, relative);
        resolved.add(locale ? path.join(candidate, locale) : candidate);
      }
    }

    return [...resolved];
  }

  function resolveLocaleFromRequest(request: Request): string | undefined {
    if (!i18n) return undefined;
    const url = new URL(request.url);
    const direct = resolveDocsLocale(url.searchParams, i18n);
    if (direct) return direct;

    const referrer = request.headers.get("referer") ?? request.headers.get("referrer");
    if (referrer) {
      try {
        const refUrl = new URL(referrer);
        const fromRef = resolveDocsLocale(refUrl.searchParams, i18n);
        if (fromRef) return fromRef;
      } catch {
        // ignore
      }
    }

    return i18n.defaultLocale;
  }

  function resolveChangelogDirCandidates(docsDirs: string[]): string[] {
    if (!changelogConfig.enabled) return [];

    if (path.isAbsolute(changelogConfig.contentDir)) {
      return [changelogConfig.contentDir];
    }

    return docsDirs.map((docsDir) => path.join(docsDir, changelogConfig.contentDir));
  }

  function isWithinDir(candidate: string, target: string) {
    const relative = path.relative(target, candidate);
    return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
  }

  function resolveContextFromRequest(request: Request): DocsContext {
    if (!i18n) {
      const docsDirs = resolveDocsDirCandidates();
      return {
        entryPath: entry,
        docsDirs,
        changelogDirs: resolveChangelogDirCandidates(docsDirs),
      };
    }

    const locale = resolveLocaleFromRequest(request) ?? i18n.defaultLocale;
    const docsDirs = resolveDocsDirCandidates(locale);
    return {
      entryPath: entry,
      locale,
      docsDirs,
      changelogDirs: resolveChangelogDirCandidates(docsDirs),
    };
  }

  const indexesByLocale = new Map<string, DocsSearchSourcePage[]>();
  const llmsCacheByLocale = new Map<string, { llmsTxt: string; llmsFullTxt: string }>();
  const markdownSourcesByLocale = new Map<
    string,
    ReturnType<typeof createFilesystemDocsMcpSource>[]
  >();

  function getIndexes(ctx: DocsContext) {
    const key = ctx.locale ?? "__default__";
    const cached = indexesByLocale.get(key);
    if (cached) return cached;

    let next: DocsSearchSourcePage[] = [];
    for (const docsDir of ctx.docsDirs) {
      const excludedDirs = ctx.changelogDirs.filter((dir) => isWithinDir(dir, docsDir));
      const docsPages = scanDocsDir(docsDir, ctx.entryPath, ctx.locale, excludedDirs);
      if (docsPages.length === 0) continue;

      next = docsPages;
      break;
    }

    if (changelogConfig.enabled) {
      const changelogPages = ctx.changelogDirs.flatMap((dir) =>
        scanChangelogDir(dir, ctx.entryPath, changelogConfig.path, ctx.locale),
      );
      next = [...next, ...changelogPages];
    }

    indexesByLocale.set(key, next);
    return next;
  }

  function getMarkdownSources(ctx: DocsContext) {
    const key = ctx.locale ?? "__default__";
    const cached = markdownSourcesByLocale.get(key);
    if (cached) return cached;

    const sources = ctx.docsDirs.map((docsDir) =>
      createFilesystemDocsMcpSource({
        rootDir: root,
        entry: ctx.entryPath,
        contentDir: docsDir,
      }),
    );
    markdownSourcesByLocale.set(key, sources);
    return sources;
  }

  async function getMarkdownDocument(ctx: DocsContext, requestedPath: string) {
    for (const source of getMarkdownSources(ctx)) {
      const page = findDocsMcpPage(ctx.entryPath, await source.getPages(), requestedPath);
      if (page) return renderMarkdownDocument(page);
    }

    const normalizedRequest = normalizeRequestedMarkdownPath(ctx.entryPath, requestedPath);
    const fallbackPage = getIndexes(ctx).find(
      (page) => normalizeUrlPath(page.url) === normalizedRequest,
    );
    if (fallbackPage) return renderMarkdownDocument(fallbackPage);

    for (const page of getIndexes(ctx)) {
      const slug = normalizePathSegment(
        page.url.replace(/^\/+/, "").replace(`${ctx.entryPath}/`, ""),
      );
      const requestedSlug = normalizePathSegment(
        requestedPath.replace(/^\/+/, "").replace(/\.md$/i, ""),
      );
      if (slug === requestedSlug) return renderMarkdownDocument(page);
    }

    return null;
  }

  function getLlmsContent(ctx: DocsContext) {
    const key = ctx.locale ?? "__default__";
    const cached = llmsCacheByLocale.get(key);
    if (cached) return cached;
    const next = generateLlmsTxt(getIndexes(ctx), {
      siteTitle: llmsConfig.siteTitle ?? "Documentation",
      siteDescription: llmsConfig.siteDescription,
      baseUrl: llmsConfig.baseUrl ?? "",
    });
    llmsCacheByLocale.set(key, next);
    return next;
  }

  return {
    /**
     * GET handler — search, llms.txt, or llms-full.txt depending on query params.
     */
    async GET(request: Request) {
      const ctx = resolveContextFromRequest(request);
      const url = new URL(request.url);
      if (resolveAgentSpecRequest(url)) {
        return Response.json(
          buildAgentSpec({
            origin: url.origin,
            entry,
            i18n,
            search: searchConfig,
            mcp: mcpConfig,
            feedback: agentFeedbackConfig,
            llms: llmsConfig,
          }),
          {
            headers: {
              "Cache-Control": "public, max-age=0, s-maxage=3600",
              "X-Robots-Tag": "noindex",
            },
          },
        );
      }

      const agentFeedbackRequest = resolveAgentFeedbackRequest(url, agentFeedbackConfig);

      if (agentFeedbackRequest) {
        if (agentFeedbackRequest.kind === "submit") {
          return Response.json(
            { error: "Method Not Allowed" },
            {
              status: 405,
              headers: {
                Allow: "POST",
              },
            },
          );
        }

        return new Response(JSON.stringify(agentFeedbackConfig.schema, null, 2), {
          headers: {
            "Content-Type": "application/schema+json; charset=utf-8",
            "Cache-Control": "public, max-age=0, s-maxage=3600",
            "X-Robots-Tag": "noindex",
          },
        });
      }

      const markdownRequest = resolveMarkdownRequest(entry, url, request);

      if (markdownRequest) {
        const document = await getMarkdownDocument(ctx, markdownRequest.requestedPath);

        if (!document) {
          return new Response("Not Found", {
            status: 404,
            headers: {
              "Content-Type": "text/plain; charset=utf-8",
              "X-Robots-Tag": "noindex",
            },
          });
        }

        return new Response(document, {
          headers: {
            "Content-Type": "text/markdown; charset=utf-8",
            "Cache-Control": "public, max-age=0, s-maxage=3600",
            "X-Robots-Tag": "noindex",
          },
        });
      }

      const llmsFormat = resolveLlmsTxtFormat(url);
      if (llmsFormat === "llms") {
        return new Response(getLlmsContent(ctx).llmsTxt, {
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, max-age=3600",
          },
        });
      }

      if (llmsFormat === "llms-full") {
        return new Response(getLlmsContent(ctx).llmsFullTxt, {
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, max-age=3600",
          },
        });
      }

      const query = url.searchParams.get("query")?.trim();
      if (!query) {
        return new Response(JSON.stringify([]), {
          headers: { "Content-Type": "application/json" },
        });
      }

      const results = await performDocsSearch({
        pages: getIndexes(ctx),
        query,
        search: resolveSearchRequestConfig(searchConfig, request.url),
        locale: ctx.locale,
        pathname: url.searchParams.get("pathname") ?? undefined,
        siteTitle: llmsConfig.siteTitle ?? "Documentation",
      });

      return new Response(JSON.stringify(results), {
        headers: { "Content-Type": "application/json" },
      });
    },

    /**
     * POST handler — AI chat with RAG.
     * Body: `{ messages: [{ role: "user", content: "How do I …?" }] }`
     * Response: SSE stream of chat completion chunks.
     */
    async POST(request: Request): Promise<Response> {
      const agentFeedbackRequest = resolveAgentFeedbackRequest(
        new URL(request.url),
        agentFeedbackConfig,
      );

      if (agentFeedbackRequest) {
        if (agentFeedbackRequest.kind === "schema") {
          return Response.json(
            { error: "Method Not Allowed" },
            {
              status: 405,
              headers: {
                Allow: "GET",
              },
            },
          );
        }

        const parsed = await parseAgentFeedbackData(request);
        if (!parsed.ok) return parsed.response;

        const payloadError = validateAgentFeedbackPayload(
          parsed.data.payload,
          agentFeedbackConfig.payloadSchema,
        );
        if (payloadError) {
          return Response.json({ error: payloadError }, { status: 400 });
        }

        if (!agentFeedbackConfig.onFeedback) {
          return Response.json({ ok: true, handled: false }, { status: 202 });
        }

        await agentFeedbackConfig.onFeedback(parsed.data);
        return Response.json({ ok: true, handled: true }, { status: 201 });
      }

      if (!aiConfig.enabled) {
        return Response.json(
          {
            error:
              "AI is not enabled. Set `ai: { enabled: true }` in your docs.config to enable it.",
          },
          { status: 404 },
        );
      }

      const ctx = resolveContextFromRequest(request);
      return handleAskAI(request, getIndexes(ctx), aiConfig);
    },
  };
}

/**
 * Create MCP route handlers for `/api/docs/mcp`.
 *
 * Returns `{ GET, POST, DELETE }` for use in a Next.js route handler.
 */
/**
 * @deprecated Prefer `createDocsMCPAPI` from `@farming-labs/next/api` in Next.js apps.
 * The `@farming-labs/theme/api` path is kept for compatibility and will be phased out.
 */
export function createDocsMCPAPI(options: DocsMCPAPIOptions = {}) {
  const rootDir = options.rootDir ?? process.cwd();
  const entry = options.entry ?? readEntry(rootDir);
  const appDir = getNextAppDir(rootDir);
  const contentDir = options.contentDir ?? path.join(appDir, entry);
  const navTitle =
    typeof options.nav?.title === "string" && options.nav.title.trim().length > 0
      ? options.nav.title
      : "Documentation";

  const source = createFilesystemDocsMcpSource({
    rootDir,
    entry,
    contentDir,
    siteTitle: navTitle,
    ordering: options.ordering,
  });

  const handlers = createDocsMcpHttpHandler({
    source,
    mcp: options.mcp ?? readMcpConfig(rootDir),
    search: options.search,
    defaultName: navTitle,
  });

  return {
    GET(request: Request) {
      return handlers.GET({ request });
    },
    POST(request: Request) {
      return handlers.POST({ request });
    },
    DELETE(request: Request) {
      return handlers.DELETE({ request });
    },
  };
}
