/**
 * Search index builder for @farming-labs/fumadocs.
 *
 * Scans MDX files in the docs entry folder and builds a search index
 * compatible with fumadocs-core's `createSearchAPI`.
 *
 * This is used internally by the auto-generated search API route.
 *
 * @example
 * ```ts
 * // app/api/search/route.ts (auto-generated by withDocs)
 * import { createDocsSearchAPI } from "@farming-labs/fumadocs/search";
 * export const { GET } = createDocsSearchAPI();
 * ```
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { createSearchAPI } from "fumadocs-core/search/server";

interface SearchIndex {
  title: string;
  description?: string;
  content: string;
  url: string;
}

/**
 * Read the docs entry path from docs.config.ts[x] at the project root.
 */
function readEntry(root: string): string {
  const exts = ["tsx", "ts", "jsx", "js"];
  for (const ext of exts) {
    const configPath = path.join(root, `docs.config.${ext}`);
    if (fs.existsSync(configPath)) {
      try {
        const content = fs.readFileSync(configPath, "utf-8");
        const match = content.match(/entry\s*:\s*["']([^"']+)["']/);
        if (match) return match[1];
      } catch {
        // fall through
      }
    }
  }
  return "docs";
}

/**
 * Strip MDX/JSX syntax and frontmatter, returning plain text content.
 */
function stripMdx(raw: string): string {
  const { content } = matter(raw);
  return (
    content
      // Remove import/export statements
      .replace(/^(import|export)\s.*$/gm, "")
      // Remove JSX tags (self-closing and block)
      .replace(/<[^>]+\/>/g, "")
      .replace(/<\/?[A-Z][^>]*>/g, "")
      // Remove HTML tags
      .replace(/<\/?[a-z][^>]*>/g, "")
      // Remove markdown links but keep text: [text](url) → text
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      // Remove images
      .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
      // Remove heading markers
      .replace(/^#{1,6}\s+/gm, "")
      // Remove bold/italic markers
      .replace(/(\*{1,3}|_{1,3})(.*?)\1/g, "$2")
      // Remove code fences
      .replace(/```[\s\S]*?```/g, "")
      // Remove inline code backticks
      .replace(/`([^`]+)`/g, "$1")
      // Remove blockquote markers
      .replace(/^>\s+/gm, "")
      // Remove horizontal rules
      .replace(/^[-*_]{3,}\s*$/gm, "")
      // Collapse whitespace
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

/**
 * Recursively scan a docs directory and build search indexes.
 */
function scanDocsDir(docsDir: string, entry: string): SearchIndex[] {
  const indexes: SearchIndex[] = [];

  function scan(dir: string, slugParts: string[]) {
    if (!fs.existsSync(dir)) return;

    // Check for page.mdx in this directory
    const pagePath = path.join(dir, "page.mdx");
    if (fs.existsSync(pagePath)) {
      try {
        const raw = fs.readFileSync(pagePath, "utf-8");
        const { data } = matter(raw);
        const title = (data.title as string) || slugParts[slugParts.length - 1]?.replace(/-/g, " ") || "Documentation";
        const description = data.description as string | undefined;
        const content = stripMdx(raw);
        const url = slugParts.length === 0 ? `/${entry}` : `/${entry}/${slugParts.join("/")}`;

        indexes.push({ title, description, content, url });
      } catch {
        // skip unreadable files
      }
    }

    // Scan subdirectories
    let entries: string[];
    try {
      entries = fs.readdirSync(dir);
    } catch {
      return;
    }

    for (const name of entries.sort()) {
      const full = path.join(dir, name);
      try {
        if (fs.statSync(full).isDirectory()) {
          scan(full, [...slugParts, name]);
        }
      } catch {
        // skip
      }
    }
  }

  scan(docsDir, []);
  return indexes;
}

/**
 * Create a search API route handler that automatically indexes all MDX
 * pages in your docs entry folder.
 *
 * Drop this into `app/api/search/route.ts` (auto-generated by `withDocs`):
 *
 * ```ts
 * import { createDocsSearchAPI } from "@farming-labs/fumadocs/search";
 * export const { GET } = createDocsSearchAPI();
 * ```
 *
 * @param options - Optional overrides
 * @param options.entry - Docs entry folder (default: read from docs.config)
 * @param options.language - Search language (default: "english")
 */
export function createDocsSearchAPI(options?: {
  entry?: string;
  language?: string;
}) {
  const root = process.cwd();
const entry = options?.entry ?? readEntry(root);
  const docsDir = path.join(root, "app", entry);
  const language = options?.language ?? "english";

  const indexes = scanDocsDir(docsDir, entry);

  return createSearchAPI("simple" as const, {
    language,
    indexes,
  } as any);
}
