// Auto-generated by @farming-labs/next — do not edit manually.

import { createDocsSearchAPI } from "@farming-labs/fumadocs/search";

export const { GET } = createDocsSearchAPI();

export const revalidate = false;
