// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { createNextApiReferenceLayout } from "@farming-labs/next/api-reference";

const ApiReferenceLayout = createNextApiReferenceLayout(docsConfig);

export default ApiReferenceLayout;
