// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { createDocsMCPAPI } from "@farming-labs/theme/api";

export const { GET, POST, DELETE } = createDocsMCPAPI({
  entry: docsConfig.entry,
  contentDir: docsConfig.contentDir,
  nav: docsConfig.nav,
  ordering: docsConfig.ordering,
  mcp: docsConfig.mcp,
});

export const revalidate = false;
