// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { changelogEntries } from "./__changelog.generated";
import {
  createNextChangelogIndexMetadata,
  createNextChangelogIndexPage,
} from "@farming-labs/next/changelog";

export const metadata = createNextChangelogIndexMetadata(docsConfig);

const ChangelogPage = createNextChangelogIndexPage(docsConfig, changelogEntries);

export default ChangelogPage;
